### ISSUE TITLE
Elegant error: p has no unit

### ISSUE THREAD

**Issue by anusornl** [radiasoft/sirepo#1029]
I got this error after importing sdds beam distribution
https://uspas-sirepo.radiasoft.org/elegant#/visualization/IshhpS0v

**Comment by robnagler** [comment]
Possibly related to:

```text
Jan 17 20:58:21   212 21673 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:298:_f
ind_job nslmSXNy-3soYZZ6J-bunchReport4: deleted errant or ready job; tid=8813ac77-6e4f-443b-aa81-55048d87081f ready=True
216.54.110.228 - li-nslmSXNy [17/Jan/2018:20:58:21 +0000] "POST /run-status HTTP/1.1" 200 201115 "https://uspas-sirepo.radiasoft.org/elegant" "Mozilla/5.0 (X1
1; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
```

**Comment by moellep** [comment]
This is a warning from elegant if the bunch input file is missing units. It is only a warning and still produces output.

In this case sddsquery shows:
```
NAME            UNITS
p               NULL
```
rather than
```
NAME            UNITS
p               m$be$nc
```

sirepo/elegant should be updated show "elegant Warnings" rather than "elegant Errors" if the parsed log only includes warnings to avoid confusion.

**Comment by anusornl** [comment]
It is working, Thank you
