### ISSUE TITLE
Simulations not completing

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1045]
These two simulations did not complete:

* https://uspas-sirepo.radiasoft.org/elegant#/lattice/pylVB2Xs 
* https://uspas-sirepo.radiasoft.org/elegant#/visualization/FWDuuxEt

@bruhwiler said they took copies of his simulation doing same thing and it worked. I looked and didn't see anything amiss. Not a rush, but should be looked at.

**Comment by moellep** [comment]
The second simulation (FWDuuxEt) reproduces a problem. If a HISTOGRAM element in the beamline has no output file, then Pelegant print an error in the logs but will run forever. Changing the simulation to serial, and it will fail and exit. 

To fix the problem, the output file should automatically get assigned when then element is created, similar to WATCH elements.

**Comment by cchall** [comment]
@bruhwiler 
The first simulation has several issues in setup.
The cavity frequency has been set to 2.856 THz. If you fix this particles do reach the end of the beamline and show a plot in output. 
The result will still be odd looking though because the cavities are being run at crossing.

(Also the linac cells are too long if this is supposed to match up with my template)

**Comment by bruhwiler** [comment]
Thanks for those pointers @cchall 
The simulation was generated by a student in a class, so not too surprising there were some problems in the setup.
