### ISSUE TITLE
SRW:  502 Bad Gateway on beta server

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1069]
Failing simulation: https://beta.sirepo.com/srw#/source/TKOSbDp1. Possible reason - it was prepared under alpha channel, can be due to the brightness report is not available on beta.

**Comment by moellep** [comment]
The problem is the simulation.facility was unused and removed from the schema recently, but the software running on beta is still expecting to see that field. Importing from an old system to a new system should always work due to the fixups, but when going from new to old could cause this problem. Schema changes like this should probably be done in phases, first to give the unused field a default value, and then to remove it.

```
Feb 12 08:11:36   212 48639 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py:198:__init__ CsCZcfiK-TKOSbDp1-intensityReport: created
Feb 12 08:11:36   212 48639 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/uri_router.py:174:_dispatch run-simulation: error: Exception: no value for field "facility" and no default value in schema
```

**Comment by mrakitin** [comment]
Oh, I see. It was hard to me to guess the reason, thanks for explaining here. Of course, we don't support forward-compatibility, just backward-compatibility. Why not to release beta with current Alpha version? Are there any developments which prevent this?

**Comment by moellep** [comment]
alpha is unstable at the moment and needs a few more bug fixes before it is ready to go to beta. Hopefully this will happen this week. If you have a dataset which needs to go from alpha to beta in the meantime, you can edit the sirepo-data.json file contained in the exported zip file and add "facility": "" to the simulation model.
