### ISSUE TITLE
SRW: create direct links to partially-coherent report page

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1074]
It was discussed via emails. The idea is to have a direct link to a partially-coherent simulation, so that it can be shared. This issue should accompany #1070.

**Comment by moellep** [comment]
Also, when sharing a simulation, the target simulation should go to the selected page in the link. For example, if a link to the SRW beamline is clicked and the simulation is copied between sessions, the beamline page should be shown, rather than the source page.

**Comment by moellep** [comment]
Just to clarify - there are two parts to this issue:

- If you are on the SRW partially coherent tab on the Beamline page and bookmark the URL, using the bookmark should display the partially coherent tab, rather than the normal beamline reports.
- If you share a simulation link, the recipient should arrive at the same page. Currently, if you share a simulation link to the Beamline page, the new copy shows the Source page.
