### ISSUE TITLE
NFS sync on open files

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1094]
On beta, there is a noticeable lag on status files which remain open during a simulation run. For example, in JSPEC, it writes full particle files at certain intervals, but also writes to a single beam summary file, adding a new line each iteration. The individual particle files show up quickly over NFS, but the single beam file takes 45 seconds or so between updates. On alpha the single beam file gets updated immediately. 

As a work-around, the JSPEC app displays a "Output file is not yet available" when the particle data is available, but the beam file is missing. Below is an example which shows the problem. Run the simulation on the Visualization page.

https://beta.sirepo.com/jspec#/visualization/2Mv0OKQi

**Comment by robnagler** [comment]
This is due to OS & NFS (& possibly stdio) buffering. We don't want to improve the interactive performance by forcing writes to be synchronous to the server, especially if they are a line at at time. This will kill "normal" performance for the large files that are written in the same directory. We are using NFS 4.1 which has many parameters for tuning performance. RHEL 7/CentOS, for example, sets the read/write size 64K by default. The kernel will buffer as much as it "reasonably" can before writing. NFS 4.1 also has "delegation", which may be at play here. [Long article here.](https://pdfs.semanticscholar.org/0994/bc95113a0216a2463a25f94372e7875b4dd5.pdf)

The solution is to implement an "agent" that monitors the process on the the "worker". It would then write to an MQ-style IPC mechanism (e.g. RabbitMQ, ZeroMQ). The server would listen and update state based on the events. This way we aren't relying on the multilayered and complex mechanism of distributed file I/O for IPC. We need this agent anyway to start and monitor jobs better than Celery does now.

**Comment by moellep** [comment]
A short-term work-around might be copying the open file to secondary file when checking status - the closed file should show up faster across NFS.

**Comment by moellep** [comment]
The previous comment won't work because the status is being checked on the server which doesn't have the latest file. A simple agent on the execution side could copy the open file every few seconds instead, assuming the status file is small.

**Comment by robnagler** [comment]
Job supervisor holds the state and there are no files, just IPC.
