### ISSUE TITLE
SRW: beamline tab:  propagation parameters do not control the initial drift

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1123]
To see the problem, start with the standard Sirepo/SRW example: "Ellipsoidal Undulator Example"
Go to the beamline page.
There are no optical elements, so all you see is the "Initial Intensity Report" at the default 20 m location.
Note that there is no option to edit the propagation parameters.
Also, it is impossible to change the location of the "Initial Intensity Report", which is kind of odd and annoying. If that's all the user wants to do, then of course they can do it on the source page. However, it might make more sense to not show any report at all on the beamline page, when there are no optical elements, rather than creating one at a (seemingly random) location of 20 m, which the user then cannot change in any way.

If you go back to the Source page and change the location of the "Intensity Report" to 10 m, and then return to the Beamline page, you will now see that the "Initial Intensity Report" has been moved to 10 m as well.

Now it's clear that the initial choice of 20 m was not really random, but is tied to the location of the "Intensity Report" on the source page.

Now drag a lens element to the "beamline definition area", set it's position to 30 m, and save changes.
Two things happen:
1) The "Initial Intensity Report" is recalculated at a position of 30 m. So now it's location is determined by the position of the first optical element, and it ignores the location of the "Intensity Report" on the source page. Here, one can observe that the size of the mesh in the "Initial Intensity Report" was not correctly resized for the new location, and therefore, the X-ray wavefront is getting clipped.
2) The "propagation" button has now appeared in the upper right corner of the "beamline definition area".

Click the "propagation" button, and you get the popup window for editing the SRW propagation parameters. However, there is no row for the initial drift (from source to 30 m) and, therefore, it is not possible to fix the problem.

All subsequent wavefront calculations will be physically incorrect, because the wavefront is being clipped just before the lens.

This is the bug.

A workaround is to create a watchpoint at 10 m.
Now the location of the "Initial Intensity Report" resets itself to 10 m (the location of the first optical element), and you don't see any clipping of the wavefront.
Also, if you click on the "Propagation" button, you will see that there is now a row for the drift region from 10 m to 30 m, which is labeled as "Drift 20m".
The user still doesn't have any control over what happens with the propagation from the source to 10 m. Presumably this is being addressed on the Source page. My understanding is that the calculation of the initial wavefront (i.e. at 10 m in this case) is decoupled from the calculation of subsequent wavefront propagation.

If you add another Watchpoint at 30 m (to the left of the lens), you will see the new report "Intensity Watchpoint Report, 30m" which looks good, with no clipping of the wavefront.

If you now delete the first Watchpoint (at 10 m), the "Initial Intensity Report" automatically changes its location to 30 m (the location of the first optical element) and now you see that radiation wavefront is being clipped again.

This strange behavior is clearly not what we want.

If you again select the "Propagation" button, you will see that the table of SRW propagation parameters no longer includes a row for the initial drift.  Hence, there is no way to correct the problem of the clipped wavefront.

**Comment by moellep** [comment]
If you only need the initial propagation parameters for scale adjustments, it would be better to adjust the "range of position" values on the "Initial Wavefront SImulation Grid" from the cog wheel menu. You can also adjust the position of the initial intensity report if there are no beamline elements from that dialog.

For example, if I have the beamline starting at 50m, but notice the initial intensity is getting clipped, the "range of position" can be changed from the defaults of 0.4, 0.6 to 1, 1 and the full wavefront will fit.

I like the idea of not showing the initial intensity report until a beamline item is present. I also think the "Initial Wavefront Simulation Grid" panel needs to get moved to the editor for the Initial Intensity Report because that would be a more natural place to look for parameters affecting the wavefront at the start of the beamline.

**Comment by bruhwiler** [comment]
I suggest the following changes:
1) The "Initial Intensity Report" should always track the position of the "Intensity Report" on the Source page. It should ignore the location of the first optical element on the Beamline page.
2) The "nominal position" value of all optical elements on the beamline page should not be allowed to be smaller than the location of the "Initial Intensity Report"

It makes sense to me that what happens on the 'Beamline' page begins with the wavefront calculated on the Source page.

**Comment by ochubar** [comment]
To my opinion, the initial intensity report should be made just before the first optical element - to save CPU efforts and problems with propagation params. This should not be linked to any settings in the Source page, but may coincide, E.g. the initial longitudinal  position could be taken from there (instead of using the hardcoded value of 20 m).

**Comment by bruhwiler** [comment]
The solution is go to the cogwheel in the upper right of the browser and select
"Initial Wavefront Simulation Grid"
In this popup window, click "Manual"
Then increase the Horizontal and Vertical values for "Range of Position"

I'm closing this issue, because there is no bug.
Instead it's a question of improving the UI.
