### ISSUE TITLE
SRW:  Intensity report is timing out

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#1170]
This is based on the Young's double slit example:
https://beta.sirepo.com/srw#/beamline/HiIA6OlI

![image](https://user-images.githubusercontent.com/3825435/39078013-52596ec6-44c3-11e8-81a2-dd92bae58e0a.png)

**Comment by moellep** [comment]
The problem seems to be the propagation parameters are making the grid too big. Changing the "4" values to 1 and it completes, although the result file is very large.

![screen shot 2018-04-27 at 1 40 53 pm](https://user-images.githubusercontent.com/6516910/39381956-1f885134-4a21-11e8-90e8-d85f5e085e9c.png)

**Comment by bruhwiler** [comment]
OK, thanks.  

I don't remember changing the propagation parameters, but maybe I did at one point.

At some point we need to (perhaps) detect the source of the difficulty and give the user some hints regarding what might be causing the problem.

I'm closing this issue.
