### ISSUE TITLE
SRW: show beamline physical layout

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1199]
I thought there was an issue for this, but didn't find it, so I'll add this one.

On the SRW (and Shadow) beamline page, there should be a way to view the physical layout of the beamline, similar to the lattice view on the elegant app.

**Comment by bnash** [comment]
This would be a great additional feature.  At the moment, I don't know if global geometry is available in SRW.  If not, adding it would be an important improvement.  The issue is similar in Elegant.  The tracking algorithms don't need the global information, so that information has to be computed separately.
