### ISSUE TITLE
Synergia: Plot turn counter inconsistencies 

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1227]
When running the 'IOTA 6-6 with NL Element' example the default 'beam diagnostics per turn period' setting is 5. However, the beam phase space plot is a little inconsistent on the intervals it shows. It displays turns 0,1,6,11,16,21,25,30... . It also seems to not include the final phase space plot of turn 50 and will stop at turn 45.

**Comment by moellep** [comment]
The odd interval 0,1,6,11,16,21,25,30,...45 was displayed due to a rounding bug - it should have been 0,1,6,11,16,21,26,31...46  Synergia always starts the count a 1 for some reason, so the last particle file will not be the end state unless "turn count" -1 % "turn period" == 0. i.e. a turn count of 51 would include the last state for a turn period of 5.
