### ISSUE TITLE
importArchive fails with empty cookies

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1329]
With the new cookie implementation, clicking on an archive html file and then importing to a server will fail with a forbidden error unless the browser has been previously cookied.

**Comment by robnagler** [comment]
This is a general workflow problem, because we may eventually require a login to upload to a server.

**Comment by robnagler** [comment]
I think this problem permeates oauth. There is an assumption that certain api_xxx will be hit before others. For example, api_findByName will handle oauth set_default_state but not api_listFiles. This special casing is problematic.

I think sirepo.oauth needs to be more robust to handle cases when it is not properly initialized and sirepo.server shouldn't be involved at all unless the api is specifically about logging in/out. 

bluesky is different, because it is logging in and executing an operation. It needs to assume there's no state.

importArchive (this issue) is similar to bluesky in that a user will need to be created. However, we can treat this like  and right before save_new_simulation in do_form, we allow the creation of a user with the same call as in bluesky (in the cookie branch).
