### ISSUE TITLE
warpvnd: Field Comparison Report "terminates unexpectedly"

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#1387]
I am constructing 3D simulation with a grid for demonstration purposes. The simulation may be found at [https://alpha.sirepo.com/warpvnd#/source/nPjECmaK](https://alpha.sirepo.com/warpvnd#/source/nPjECmaK).

When constructing the simulation, the Field Comparison Report gives the error "Terminated Unexpectedly." I suspect that running generate() with large grids may result in a timeout.

**Comment by bruhwiler** [comment]
Not finishing after 30 minutes (or 3 hours) is fine under the following conditions:
1) the user is given a realistic estimate of the run time
2) the user has the option to kill the job, if they get impatient

Ideally, Sirepo would routinely estimate the time required for any simulation.

**Comment by robnagler** [comment]
I would add that we should modify the write frequency of files on large jobs.

**Comment by moellep** [comment]
This report has been changed to a background job so it can be started and canceled manually. It will run with MPI if the parallel execution has been selected for the simulation. It produces no output or logging for a really long time due to the grid size (100x100x500) so it isn't possible to estimate the completion without adding more logging.
