### ISSUE TITLE
Create test for job queue and complete

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1427]
Tests a single job of myapp with runner.process.

Use one of the `pytest` examples in sirepo or pykern as a basis.

**Comment by njsmith** [comment]
Adding in some more information from email:

We run pytest under py2 when building the docker image, or when people manually run `test.sh`. The testing here will require a bit of reorganization, because the runner daemon is py3-only, and we call into it from the py2 server code.

I guess the general outline will be:

* Use `pyenv global py2:py3` to set things up so that we have `python` and `pip` pointing to the current python 2 environment, and `python3` and `pip3` pointing to the new python 3 environment.
* Use `pip3` to install the runner daemon's dependencies
* Arrange the code so that the flask side (runner client) is py2 compatible, and the py3-only code is restricted to `sirepo.pkcli.runner`.
* Then the py2 tests can start a runner daemon in the background with something like `subprocess.Popen(["python3", "-m", "sirepo", "service", "runner-daemon"])` (possibly as a pytest fixture), use the py2-compatible client APIs from inside pytest to talk to it and make sure it works, and then close it again.
