### ISSUE TITLE
elegant: small lattice visualization issue

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#1486]
For beamlines with very small physical sizes (millimeter scale) it appears that the lattice visualization does not properly resolve all the elements.

Example here: https://beta.sirepo.com/elegant#/lattice/6Dn9AyWY
The lattice viewer just shows one quadrupole, not the five that are in the line, no matter how much I zoom in.

Note, this is only an issue in the lattice viewer. Post-simulation plotting all appears correct.

**Comment by moellep** [comment]
I made a minor fix which helps. The problem was the outline of the magnet was wider than the magnet itself. The lattice is still squished together, but at least the individual elements can be discerned.

![lattice-bl1-1](https://user-images.githubusercontent.com/6516910/50497589-4540f300-09f6-11e9-8a54-9895bdcd73c9.png)
