### ISSUE TITLE
SIREPO server problem?

### ISSUE THREAD

**Issue by marlibgin** [radiasoft/sirepo#1496]
Hello, 
 I am not sure this classifies as a bug, however I have a very simple simulation [https://beta.sirepo.com/srw#/beamline/LCD8K6oI] that was running yesterday until 16:00 (GMT) and literally stopped running after that. Today (15/1/2018, 9:00 GMT) seems to be back but all 's extremely slow. It starts running but gives a "unexpected error (see log)" message. Is there any server problem? Thanks for your attention.

**Comment by robnagler** [comment]
I think this might be related to result size. The output at 16:30:25 returned was 236,525,477 bytes. The maximum return value is set to 200MB. I need to discuss internally what a reasonable size is for expected results.

Possibly related, some of the run-simulation requests seemed overly large:

```txt
14/Jan/2019:00:57:18 +0000] "POST /run-simulation HTTP/1.1" 200 1426844
14/Jan/2019:08:34:33 +0000] "POST /run-simulation HTTP/1.1" 200 21346657
14/Jan/2019:08:34:44 +0000] "POST /run-simulation HTTP/1.1" 200 21168807
```

**Comment by marlibgin** [comment]
Thanks very much Rob.
At least I am getting some clue about it. I guess is related to the resolution adopted or so, I am a bit surprised cause it seemed to be a very
 Simple case.

Thanks again
Marco

**Comment by robnagler** [comment]
We are looking the simulation itself.

**Comment by moellep** [comment]
The selected sampling factor appears to be the main problem. If you reduce the sampling factor from 2 to 0.5, the simulation should run OK. Reducing the sample factor, and the "Range of Position" on the "Initial Wavefront" should help. Additionally, each beamline report can be rescaled by setting the "Maximum Plot Dimension" value on the Scale tab. That will reduce the time waiting for the large datafile to transfer over the network.

![screen shot 2019-01-15 at 10 16 09 am](https://user-images.githubusercontent.com/6516910/51197377-98e48500-18ae-11e9-9212-a9727594e99a.png)

The propagation parameter resolution values can also have a big impact on the file size. Reducing the range rather than increasing the scale may help at certain points in the beamline.

Below is a slightly modified simulation which should run OK.

https://beta.sirepo.com/srw#/beamline/OpSqlxR2

**Comment by marlibgin** [comment]
Thanks everyone for this prompt reaction! Just a comment. The initial example was taken from SIREPO website Examples directory [Gaussian X-ray beamline containing imperfect mirrors], and the initial wavefront for that case was already set to 2. I am actually trying to find some documentation on the use of this and other parameters (essentially propagation factors). Does it exist?

**Comment by nickgoldring** [comment]
Hi Marco,

The sampling factor of 2 in the Sirepo example _Gaussian X-ray beamline containing imperfect mirrors_ was suitable for calculating the wavefront at 270 m.  However, when you modify the beamlines to compute the initial wavefront at 15 meters, a smaller sampling factor is required.  

Currently, no comprehensive manual exists to describe exactly how to set all such parameters.  Some expertise in Fourier optics and understanding of the underlying code are required.

In addition to running examples in Sirepo, one can also look into the [Python calls](https://github.com/ochubar/SRW/blob/master/env/work/srw_python/srwlib.py) to gain familiarity. Please see [this Jupyter notebook](https://github.com/radiasoft/SRW-Support/blob/master/Examples/GsnSampFactTest.ipynb) where we have created a Gaussian wavefront at 15 meters with varying sampling factor.  You can run this notebook using [RadiaSoft's Jupyter server](https://jupyter.radiasoft.org/).

A plot contained within the notebook shows a linear relationship between the sampling factors and number of grid points used for the calculation.

![nPointsVsSampFact02](https://user-images.githubusercontent.com/32494032/54400781-20215f80-468a-11e9-85bc-dc33d6fbb745.PNG)

Hopefully this helps to address your question.  Please let us know if you have any further questions.
