### ISSUE TITLE
questionable write_parameters implementations

### ISSUE THREAD

**Issue by njsmith** [radiasoft/sirepo#1545]
The `template.write_parameters` function is responsible for filling in a `run_dir` before a report runs. As part of #1539 and #1544, we need to start renaming the `run_dir` between when `write_parameters` runs, and when the actual job runs. I did a pass through all the `write_parameters` implementations, and found several that will be broken by this:

* `warppba.py`: passes the absolute `run_dir` path to the jinja2 template, as the `outputDir` parameter, which then gets written into `parameters.py`

* `rs4pi.py`: similar – hard-codes the `run_dir` path into the parameters file. Also appears to write to the `run_dir`'s *parent* directory, which seems race-y?

* `srw.py`: tries to read some data out of the `run_dir`, which definitely won't work if we're always setting pointing `run_dir` at an empty directory when generating the parameters. But, this may not matter – if I'm reading `simulation_db.prepare_simulation` right, even before my changes we're already clearing `run_dir` before calling `template.write_parameters`. So I think it's already broken, but won't get any more broken.

I guess the biggest issue is `warppba.py`. Could we write a relative directory instead?

**Comment by robnagler** [comment]
We can make a relative path for run_dir from prepare. If the program needs an absolute path, it can be converted at run time. We should fix #1313 by normalizing the code that starts a simulation to always chdir into the run_dir.

Submit a separate PR for the changes to the use of run_dir. Make them relative for now, because afaik, codes "never" chdir when they are running.

rs4pi is not in use so don't worry about it. The reaching into parent dir was a hack to avoid a large file copy in to the run_dir.

**Comment by njsmith** [comment]
#1546 should fix warppba. You said not to worry about rs4pi, and like I said above, I *think* srw isn't actually affected, so this is the main one I'm worried about.

**Comment by njsmith** [comment]
I guess this can be closed for now, unless you want to keep it open for rs4pi?

**Comment by robnagler** [comment]
rs4pi needs a lot of other work so closing is fine.
