### ISSUE TITLE
zgoubi: Need a sirepo landing page

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1572]
We need a landing page describing zgoubi which lists the award number and provides a summary and launch button.

**Comment by messamer** [comment]
I don't see this landing page on alpha.  Should the issue be closed?

**Comment by robnagler** [comment]
When you see `moellep closed this in 91c65ba a day ago`, it is closed automatically by a commit which refers to the issue.

There has not been an alpha release.

Technically, we could have more management workflow around commits, issues, and releases, but I think it would just slow things down. The commit will get pushed to production eventually. If it isn't satisfactory (along the staging pipeline), feedback is always welcome here.

**Comment by messamer** [comment]
It would be nice to have a list of all of the issues included in a particular alpha release.  I don't think that would involve a lot of overhead.

**Comment by robnagler** [comment]
I think that would be this query, which you get to by clicking on `Issues` and then `Closed`:

https://github.com/radiasoft/sirepo/issues?q=is%3Aissue+is%3Aclosed

You can see all issues that have been closed since the last alpha release..

Any branches or other work in progress is not closed until it is merged in the `master` branch. Everything in `master` is automatically put in the release. We only have one alpha release at a time so it's the most complete and accurate history.
