### ISSUE TITLE
Sirepo pip package

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1656]
Hi @radiasoft,

Are there plans to revive the pip package for Sirepo? While working with @awalter-bnl (see #1654), we ended up installing Sirepo on a debian machine directly. First attempt was `pip install sirepo`, however it pulled a very outdated version (Feb. 2018) from https://pypi.org/project/sirepo, and eventually failed the installation, so we had to clone both pykern and sirepo, and install everything from scratch, including `h5py` and `bnlcrl` (which weren't included in the required packages). It may be confusing for he growing community of Sirepo users. The PyPI packages should either be supported, or clearly marked as deprecated, so no attempts should be made to use them (ideally, when attempted to `pip install sirepo`, the best response from PyPI would be `the package not found`). I see that the pykern package is quite up to date (https://pypi.org/project/pykern/20190506.215338) though.

Given the recent problems with the Vagrant box installation (#1644), changes in Docker infrastructure (like removing `/radia-run`), and the lack of documentation on running Docker containers in production, the most reliable and easiest way for us is installing with pip (and potentially conda). Thank you.

**Comment by robnagler** [comment]
Sirepo is mostly easily used directly from [sirepo.com](https://sirepo.com). We highly encourage anyone to try this approach. For the foreseeable future, we offer this data and compute service for free.

If you still want to install locally, Sirepo is best installed with Docker. For the desktop, you can `curl sirepo.run | bash`. For Windows, we provide [instructions in the README](https://github.com/radiasoft/sirepo#manual-install-with-docker). 

For servers, the configuration is host operating system dependent. You could run Sirepo inside Docker containers running on Windows, for example. We assume people are familiar with starting Docker containers on their preferred operating system. There are many resources available on the web for running Docker including many competent system administrators, whom you can hire to help you with a local installation of Sirepo.

There are many different ways to configure Sirepo. We offer consulting services to organizations that require help. Please contact me offline if you would like help with your installation.

We are constantly improving Sirepo; this does have a cost, especially since most other packages (Vagrant, VirtualBox, Docker, etc.) are also changing rapidly.  There will be defects and failures. In the case of Vagrant for development, on Monday we discovered that the Fedora release (27) we were relying on disappeared from Vagrant Hub. On Thursday we released an upgrade to the latest release of Fedora (29) for development. There are [still problems](https://github.com/radiasoft/sirepo/issues/1644#issuecomment-491036795), but it is usable by developers, which is the only supported Sirepo channel for Vagrant. We do not support Vagrant for alpha, beta, or production use.

The Docker images for alpha, beta and production are still based on Fedora 27. We have not released a Fedora 29-based Docker image. When we do, we will announce any changes required for local installations (likely none).

Sirepo is an end-user application, which is only useful with a specific set of particle accelerator and/or beam simulation codes. Unfortunately, these codes cannot be installed with pip. Installing Sirepo from PyPI is obviously confusing to end-users, which is why it has been removed from PyPI.

**Comment by mrakitin** [comment]
I understand your business model. However, I disagree the pip-installable version should be abandoned. I don't need to hire a "competent system administrator" to do pip installs! It's just a couple of steps to compile SRW, and in the foreseeable future https://github.com/srwpy/srwpy will be available for users via `pip install srwpy`. Shadow3 is already available via `pip install shadow3` as well. So having the base Sirepo installer will be extremely useful, even for running the [codeless server](https://github.com/radiasoft/sirepo/wiki/Development#codeless-server-execution). And we are mostly interested in those 2 codes.

What's the story of https://pypi.org/project/pykern? Do you also plan to abandon it?

Can you please provide more details on what are the particular problems with making the latest Sirepo available in PyPI? As one can install the package directly from GitHub, or source install it from the cloned repo with `pip install .`, I don't think there are insuperable obstacles there. I just ran `python setup.py sdist bdist_wheel` with the latest master, and got the 2 files:
- `sirepo-20190123.123027-py2-none-any.whl`
- `sirepo-20190123.123027.tar.gz`

It's my responsibility then to compile the codes I am interested in to make them work with the base sirepo library.

If you have no budget to do that, I am happy to volunteer to take care of it (via CI configured in my fork). Please let me know.

**Comment by robnagler** [comment]
Sirepo is an end-user application deployed with 12 sophisticated beam and accelerator simulation codes. This is why we only support Docker deployments.

PyKern is a library, and will be available on PyPI for pip installs.

Both are open source, and you are more than welcome modify them.

**Comment by mrakitin** [comment]
Sorry to see this, I still don't understand why it's so difficult to include these two lines in your home-grown CI:
```bash
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

This way the core library could be made available with a much less barrier for new users.

@bruhwiler, do you have an opinion on that? Thanks.

**Comment by bruhwiler** [comment]
I understand the software team's reluctance to implement and support another distribution channel. 

When I think of the priorities for Sirepo development, based on deadlines and funded projects, I would not elevate "implementation and support of pip install" to a high level.

**Comment by mrakitin** [comment]
OK, thanks for the feedback, @bruhwiler. I think on our side we will work on our fork and will generate the pip and conda packages for NSLS-II usage.
