### ISSUE TITLE
Development mode

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1675]
It seems a simple `sirepo service http` does not work out-of-the-box anymore for the development setup. I guess it's due to the breaking changes in https://github.com/radiasoft/sirepo/issues/1626. What should be a minimal set of env vars to start the service?

Tried:
```bash
SIREPO_AUTH_METHODS=guest sirepo service http
```
however got the following error when accessing a list of simulations:
```
../sirepo/util.py:45:_raise simulation_db dir not found, deleted uid=V3Rh7qz3
../sirepo/uri_router.py:202:_dispatch simulation-list: error: Unauthorized: 401 Unauthorized: The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
```

Thank you.

**Comment by robnagler** [comment]
I think the error happened due to an existing sirepo_dev cookie. You had user `V3Rh7qz3 ` in the cookie, but there was no database entry matching that user. Perhaps you started with a completely fresh sirepo directory.  You will have login anew by going to the profile button in the upper right hand corner and clicking "Sign out". This is a developer only situation so it's unusual.

You shouldn't need to specify `SIREPO_AUTH_METHODS=guest`, that is, the default, so you should be able to just say:

```sh
sirepo service http
```

**Comment by mrakitin** [comment]
Thanks, it works fine now. Closing.
