### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by ahebnl** [radiasoft/sirepo#1723]
There is authentication error (bad gateway) errors in Fullstack Development settings.

It turns out xraylib and rslinac are missing.
I installed with a command `curl radia.run | bash -s code xraylib` and the uwsgi service error has gone and works fine.

@ochubar @mrakitin @moellep

**Comment by robnagler** [comment]
rslinac is no longer supportd. Shadow (which requires xraylib) is currently not supported, because it does not compile with gfortran 8 (Fedora 29). It might be that your radiasoft/sirepo checkout is out of date. [master does not include these codes.](https://github.com/radiasoft/sirepo/blob/e483d1e355a0e01147397a7149a7487eef588f1b/sirepo/feature_config.py#L15)  You might also check to see if `$SIREPO_FEATURE_CONFIG_SIM_TYPES` is set.

**Comment by ahebnl** [comment]
Yes, the radiasoft/sirepo checkout is around this May. We use the old checkout because we want the version of "noblue" interface :).
@robnagler @ochubar

**Comment by robnagler** [comment]
I'm sorry that you don't like the new home page. Using an old branch is not something we can support for development. You certainly can propose a simple landing page that would show up with a feature_config flag.

**Comment by ahebnl** [comment]
get it. I will pull the newest checkout and modify the landing page. thanks
for your suggestion!
An

**Comment by robnagler** [comment]
BTW, the old landing page is still there so it should be fairly easy to work from this.

**Comment by ahebnl** [comment]
That's great :)!
Thank you.

**Comment by ahebnl** [comment]
Hi bob,
Could you please give me a linker about the old landing page for the newest
master branch of sirepo? sirepo beta is ok.
Thanks,
An

**Comment by robnagler** [comment]
http://alpha.sirepo.com/old
