### ISSUE TITLE
Sirepo User Login Methods and Account Management

### ISSUE THREAD

**Issue by nickgoldring** [radiasoft/sirepo#1737]
As I understand it, the Sirepo login system on alpha allows one to either sign in using an email address + name or as a guest.  The former requires email authentication which grants the user access to Sirepo with the ability to save their simulations.  In this case, if this user does not log out then they will be able to access their saved simulations.  If they do log out, then they must repeat the email authentication process in order to regain access to the simulations.  Perhaps it is the case that most people will remain logged in and not delete their cookies for long periods of time.  However, in cases where people will be logging in and out frequently or using different computers, it could become a nuisance for them to have to re-authenticate via email each time they want to access their simulations.
 
This could potentially be remedied by implementing an account management system with usernames and passwords.  I realize that the system on beta using Github accounts for Sirepo access does not necessarily provide us with user information such as email.  Google accounts might be a good alternative as they would offer users an easy way to manage their simulations without having to remain logged in or re-authenticate each time they wanted access to their Sirepo simulations.  I don’t know how easy this would be to implement but I figured I would share my thoughts on the issue.  A related discussion is here: #1687.

**Comment by robnagler** [comment]
Thanks @nickgoldring for the feedback. I hope the following will help you understand our design choices.

We are working on the login workflow. There will be a new version soon which makes the flow better for guest. I don't think we are going to allow users to logout as guest, because this is a meaningless operation.

Most users don't logout. In the last month, there were 8 calls to logout on production from about 5 users, and some of these may have been testing from our office. We also know that most users have not bothered to registered so they are using the system as a guest, which means they probably never logout.

There are many considerations with multiple login choices. It creates confusion to have choice in user interfaces, for example. Passwords and/or which login method choice may be forgotten. Another factor to consider is that Google Accounts probably do not work in China where we have users. 

The purpose of a password-less login is to ensure multi-device access as well as any single-factor email-based authentication system can without the problems associated with multi-choice logins. It is guaranteed to work from any device from which the user has email, and the user must be on the Internet to use Sirepo so that's like to be every computer.

All authentication methods are problematic. Even without authentication, we have had cases of users getting confused about how to get at their simulations. This is one of the reasons we are going to be requiring users to authenticate and/or allow them to choose a name: it allows us to give them better customer support.

**Comment by nickgoldring** [comment]
Thanks for the explanation, Rob.  That makes sense.
