### ISSUE TITLE
warpvnd: Allow different reports to use same simulation results

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#1739]
With complicated conductors in play, highly granular cells mean that the field and field comparison reports can run for a long time, like hours.  They actually generate the same ```parameters.py``` file, so the exact same simulations get run twice.  I think we need a way to group reports so that they can use the data of their siblings.  elegant's bunch model does not work here because there is a single report, run once, that related reports sift, whereas this is two reports with different models.  It will be along the same lines, though, I expect.

**Comment by robnagler** [comment]
We definitely need to distinguish between a simulation run and a report run. These are already being handled separately in the new runner. It would be great if we came up names for these things, including the directories in which they run.

**Comment by moellep** [comment]
If a report takes longer than 5 minutes or so, it should be a simulation
instead (called animation because the first case of this was the warppba
animation frames). Reports will time-out otherwise and they also get
canceled if you leave the page. For warpvnd, we'll need to move some of the
3d reports into an animation. Animations also have the advantage that they
can show % completion and can have multiple plots all out of the same
directory - JSPEC is a simple example of this.

Paul

**Comment by robnagler** [comment]
I think we need to distinguish between:

* start simulation
* real-time status of the simulation
* start extract of report
* status of report
* return of report

These are all different messages. A simulation may have multiple reports. A report may take a long time to extract. All of these operations need to be handled asynchronously by the client and the server.

**Comment by robnagler** [comment]
To be clear, a "simulation" in Sirepo terms is the db for a collection of "simulation data and runs". For now, we have run a "job", but reports in the released runner are not jobs, and they need to be. The new runner has a concept of "extract job". There's asynchrony in extract job, which is [synchronized in the daemon](https://github.com/radiasoft/sirepo/blob/879429fd28b6c0b7137f63847b4ea10aa9c0c1bd/sirepo/runner_daemon/docker_process.py#L137) and shouldn't be.
