### ISSUE TITLE
requested changes to the email-based login workflow

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1779]
Several changes required:

- Guest users will not be prompted to enter their name.

- Guest users will not see a "Sign out" option, but instead will see "Save you work!" which directs them to the non-guest login option (email or guest depending on configuration).

- Old GitHub accounts will be redirected to sign in with email, if GitHub login is not supported through configuration.

**Comment by robnagler** [comment]
Do we want "Guest User" to be hardwired in the db as opposed to an empty display name being displayed (in the GUI) as "Guest User"?

**Comment by moellep** [comment]
I think we want to show the user as "Guest User" in the UI. The user choose the "Sign in as Guest" option and it makes it clear they aren't identified.

**Comment by messamer** [comment]
Rob-

Is this a question about how guests are stored in the DB?  I think you are
asking if, rather than putting "Guest User" as the value in the DB, you
want to leave DisplayName empty in the DB then evaluate DisplayName and, if
empty, the GUI will displays "Guest User".

Correct?
P

--
Paula Messamer
Product Manager - RadiaSoft LLC
1-720-502-3928   x719
radiasoft.net - sirepo.com

**Comment by robnagler** [comment]
Yes @messamer is correct. I am talking about the data in the db. If the user is type "guest", then we don't need to fill the display_name at "Guest User". Rather, we simply leave it blank, and render it as it makes sense (someday, it might be "Guest", for example) in the GUI. We know the user is a Guest, because that's provided by the server.

**Comment by moellep** [comment]
Yes, it could be empty in the db.
