### ISSUE TITLE
Pivot to Tornado from trio/hypercorn

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#1869]
We've decided to pivot away from trio/hypercorn/asks to Tornado. The tl;dr is Trio worked fine but the environment around it (hypercorn and asks) is still new and the kinks have yet to be worked out.

Tornado is a proven framework with a long history and numerous users. One specific benefit is that Tornado is usable in py2 and py3. This allows us to migrate code more easily to it.

### Asks (an async http client compatible with trio):
- Trio would output deprecation warnings during the use of asks. This isn't a huge problem but showed that Trio is changing and asks is unable to keep up.
### Hypercorn (an async server compatible with trio):
- During long-polling it is possible that the client may close the connection. Hypercorn did not handle this case so we were never notified and our response looked like it was succesfully sent to the client even though it was dropped on the floor by hypercorn
- Hypercorn would automatically respond to the client when we returned from the request method even when we were still holding on to the responses object. We worked around this by putting in an event wait to make sure that the method was not returned from until we had responded.

**Comment by robnagler** [comment]
@e-carlin did a great job of converting to Tornado. During this process we had some head scratching about locks. Locks in Trio have an owner. In asyncio, they don't. In Tornado, not sure.

This brought up some questions about how async/await actually works. We perused [How the heck does async/await work](https://snarky.ca/how-the-heck-does-async-await-work-in-python-3-5/) by @brettcannon, and still, it bothered me I didn't understand suspend/resume. I read [The Magic Behind Python Generator Functions](https://hackernoon.com/the-magic-behind-python-generator-functions-bc8eeea54220) by @skabbass1, which got me much closer by pointing me to the CPython source to understand what the heck yield does as well as reminding me how Python stacks work. Both articles are great reads if you care about all this stuff.

The magic is that `asyncio` sets the current eventloop in CPython via [_asyncio__set_running_loop](https://github.com/python/cpython/blob/18b711c5a7f90d88fb74748f18fa8ef49d8486c7/Modules/_asynciomodule.c#L3011). I did read [the opcode YIELD_FROM's implementation](https://github.com/python/cpython/blob/18b711c5a7f90d88fb74748f18fa8ef49d8486c7/Python/ceval.c#L2044) to figure out how yield/await works.

All the events are managed by the Python module, e.g. asyncio or curio. The loop object has a function called `call_soon` that _asynciomodule.c uses to schedule the callbacks (tasks, essentially) for the future.

Python stack frames are objects so they are linked lists. There's a back pointer, f_back which is set dynamically for the generator frame  when the generator sends its result back to the receiver to the receiving frames.

Not important really, but just documenting here, because I thought it would help.
