### ISSUE TITLE
elegant: running beam in reverse

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1882]
One use case for elegant is flipping the sign on all element values (length, angles, etc.) and running the goal beam through the elements to see what the initial beam should look like.

Sirepo doesn't render the flipped beamlines correctly, see #1819.

Flipped beamlines should appear the same as a normal beamline, but some symbol should be shown to indicate the beam is going in reverse, starting from the end.

**Comment by sdwebb** [comment]
This conversation has continued:

Youna Park at UCLA came across a bug running a simulation backwards through elegant. Sirepo is not really equipped for visualizing this, but there is also a bug in elegant itself that Michael Borland is planning to fix. Because the backwards propagation feature has come up a few times, there is a chance the next version of elegant will not only fix this bug, but also have backwards propagation be a flag in the elegant controls.

I will keep people posted as I hear more about this.
