### ISSUE TITLE
questions about warpvnd fixup

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1904]
There are [some TODOs](https://github.com/radiasoft/sirepo/blob/f81fa7da58b17fb145fa7c3c1ac5488c97cc0255/sirepo/sim_data/warpvnd.py#L48) which are questions for @mkeilman and @moellep. Maybe this can be a conversation.

**Comment by moellep** [comment]
- I don't understand the "denormalization of conductors" comments.
- There should never be a None conductorType, that code can be removed. If there was a None type, it would be a bug.
- isConductor is a '1' or '0' boolean because in the schema all Boolean types have the string value "0" or "1". Enums only allow string name/value pairs.
- Each conductor has a "type" field which could be "box" or "stl" and corresponds to a model name in the schema. This is similar to SRW which has a beamline of optical elements and the "type" field is the model name.

**Comment by robnagler** [comment]
There are `data.models.conductors` and `data.models.conductorTypes`. I am guessing that conductors refers to conductorTypes, and it would therefore be normalized, but wanted to understand.

**Comment by moellep** [comment]
The conductorType defines the geometry and properties. The conductor is the (position, type). There can be multiple conductors which share a condcutorType.
