### ISSUE TITLE
srw fixups missing beamline items

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1962]
Fixups aren't being applied to beamline items. For example, missing verticalOffset isn't be added to mirrors. This causes problems, including breaking file deletion.

**Comment by robnagler** [comment]
I don't think this fix is robust. lib_files should always have the right values. When is prepare_for_client not being called?

**Comment by moellep** [comment]
prepare_for_client() isn't called when you try to delete a file and it calls lib_files() on all simulations to see if any sim has the file.

**Comment by robnagler** [comment]
The fix then has to be that deleteFile calls api_simulationData. It should also grab the global lock, because it has to make sure that a simulation isn't saved simultaneously that uses the file. 

@e-carlin and I are seeing lots of edge cases like this that "don't happen", but then something happens, and code is added somewhere else instead of fixing the fundamental issue of not having a clear control flow over the data.
