### ISSUE TITLE
if a sequential job is canceled, is there any output?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1966]
@moellep There's a lot of code dealing with cancel, and it is messy. I think that when a sequential (transient) job is canceled, there is no output. For now, it means the report panel was closed or the tab was switched so no output would be shown after the cancel, but even if the window was opened, it will always re-run the job, I believe. Therefore, we should never return output in the cancel case for sequential (transient) reports.

Correct?

**Comment by moellep** [comment]
Yes, I think that is true - if you cancel a job, no results should be expected. Where is the message code for dealing with cancel, on the client or server?

**Comment by robnagler** [comment]
[server._simulation_run_status](https://github.com/radiasoft/sirepo/blob/97d27131fb09d8df9ea1f95ddf93cb99492aba41/sirepo/server.py#L946) is messy, but it seeps throughout by the parse_error_log checks in various places (that don't need to happen), and then [simulation_db.read_result](https://github.com/radiasoft/sirepo/blob/97d27131fb09d8df9ea1f95ddf93cb99492aba41/sirepo/simulation_db.py#L602) figuring out canceled or error.

Another question: if a job errors, do we want to show output (other than the error)? The way the code is written, it's possible that data will be returned in simulation frame.

Another weird case is frame_count for zgoubi which seems to [do a lot of checking](https://github.com/radiasoft/sirepo/blob/97d27131fb09d8df9ea1f95ddf93cb99492aba41/sirepo/template/zgoubi.py#L288) instead of "knowing" it is there. If it can't read the frame count from the simulation_db.read_result (which it doesn't call directly and instead read_json) then it calls read_frame_count. If that isn't there, it assumes it is an error and parses an error log (not with parse_error_log, but its own _parse_zgoubi_log). The result gets "errors" which seems to be a zgoubi invention, instead of "error", which other templates use.

**Comment by moellep** [comment]
I think there are a couple of different error cases. One would be a programming bug and those shouldn't get shown to the user. For example an AttributeError "'dict' object has no attribute 'x'" shouldn't be shown to the user. In these cases showing "Sever Error" would be fine.

Some errors should make it back to the user. For example if a simulation is about to be run, but it is determined that it will produce too much output, the simulation should abort with something like "Simulation output too large, reduce values X... and rerun". Other cases which should make it back is if the simulation fails and the output logs can be parsed to determine the failure.

We could use assertions for the former and UserAlert exceptions for the latter.

There is some special caching code in zgoubi for frame count because it takes a lot of time to compute that value. Parsing zgoubi output is too slow and there is another ticket for that. The caching code may not correctly written as well.

**Comment by robnagler** [comment]
@e-carlin make sure we handle this case properly: state=error means there's no output.
