### ISSUE TITLE
srw: changing existing beam doesn't recompute reports

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1967]
Changing the Existing Beam value should automatically recompute all the reports.

**Comment by moellep** [comment]
This is a special case where the report directory already exists and something goes wrong. The error log is showing "ignore other error", but the directory is not being removed, so the error happens each time an attempt is made to recompute the report.

**Comment by robnagler** [comment]
Which report?

**Comment by moellep** [comment]
Hard to reproduce, but these are the steps:

1) Undo the work-around from 5b983b3
2) Run the SRW example Undulator Radiation on the source page.
3) Edit the run file fluxReport/in.json and remove the "computeJobHash" line and the "arbitraryMagField" model.
4) Visit the simulation list and then back to the Undulator Radiation sim. A "ignore other error 'arbitraryMagField'" will appear in the logs.
5) Edit any field on the Flux Report, but it will show the error in the logs and return the old output. There isn't anyway to get the report to recompute. 

I put a TODO in 5b983b3 because I think this might affect the other return cases above the fix.

**Comment by robnagler** [comment]
I'm working on a test for this.

**Comment by robnagler** [comment]
FYI, when I remove the `except` clauses, no error appears, and everything appears to work fine.

**Comment by robnagler** [comment]
There's a lot going on here. I think the best thing is to remove the `except` clauses, because that let's the caller (`_simulation_run_status`) see the error and handle it properly. There's a check for the run directory so it won't result in an exception in the case that the run_dir doesn't exist. If in.json doesn't exist in a run_dir, it's a special case. If the in.json doesn't match the current fixups, it's a special case.

`_simulation_run_status` calls `_simulation_error` with `quiet=True`, which is a problem, because it masked the error (KeyError). 

`_simulation_run_status` is a problem @e-carlin and I were teasing apart yesterday. I think we finally understand the paths. A lot is related to lack of locking which will go away with the new job exec code (indeed _simulation_run_status goes away in its present form).

I think a test is still warranted for the "fixup" case of in.json. I'm going to commit the removal of the `try` in `report_info` (which also goes away in the new job code), which will fix this particular problem.
