### ISSUE TITLE
Login issue to Sirepo 

### ISSUE THREAD

**Issue by smlund** [radiasoft/sirepo#1987]
I was setting up runs on my lab windows desktop without issue and signed in sending lund@frib.msu.edu to make an account.  Then I tried loggin in via other computers (laptops first running linux, then osx, then a 2nd lab desktop running windows) and could not get it to accept my email and send me a link to login and see my files using lund@frib.msu.edu.    

Have I been blocked some way?!?!   

This has me puzzled because the 2 students I am working with could connect with a 2nd computer logged making a connection on another computer.  This is the way I thought it should work.  

Please check and see if I triggered some issue.  Sorry for the problem.  The bad part is I was explaining to the students could connect from anywhere and continue working on their simulations and I could not connect in a chain of tries.  But they thought it was funny and I opened a 2nd account under another email without issue.  However, I want to go back to using lund@frib.msu.edu 

Thanks! Steve

Professor Steven M. Lund
Director, US Particle Accelerator School / FNAL
Michigan State University / FRIB
517-908-7291
lund@frib.msu.edu

**Comment by smlund** [comment]
Hi Rob,


See the 3 attached screen shots of the progression.  Sorry for the odd lines that were generated by the screenshot tool used.  It happens on all computers I tried.  I request a login and then I get an expired link message immediately on first click.  This happens on 3 different computers I tried using lund@frib.msu.edu    The students had no such issues.


Doubly puzzling  to me is I was able to connect to one lab windows desktop in my office which links to lund@frib.msu.edu  and maintains that connection fine.


I just verified that I can disconnect from that account (close browser) and reconnect.  I do not want to clear the browser though or I cannot get back in my account.

Steve

________________________________

**Comment by bruhwiler** [comment]
Steve -- your screenshots did not get captured by GitHub.
Could you please go to the web interface and copy the images in directly?
Seems like email attachments might not work...
Thanks,
David

**Comment by smlund** [comment]
Here are the screenshots.  Sorry for the delay.  Thought the email sent.  
![lund_sc_1](https://user-images.githubusercontent.com/7502170/67610956-3c2ec880-f764-11e9-8dba-3a9af1bb8e7b.png)
![lund_sc_2](https://user-images.githubusercontent.com/7502170/67610957-3cc75f00-f764-11e9-9440-30f8f1d43cae.png)
![lund_sc_3](https://user-images.githubusercontent.com/7502170/67610958-3cc75f00-f764-11e9-8623-945a437efb96.png)

Not seeing them here ... but hope the links send what you need.  Not much info in the messages.  I am puzzled if you show no extra login attempts via lund@frib.msu.edu

**Comment by robnagler** [comment]
@smlund The problem is that the login link can only be used once. You will need to login to each computer, one at a time, that is, visit https://www.sirepo.com/elegant on the new computer, which redirect you to the login page:

![Screen Shot 2019-10-28 at 6 14 39 PM](https://user-images.githubusercontent.com/5495179/67727373-d3875c00-f9ae-11e9-9549-24bea4ef1a7f.png)

Enter the same email you used on the first computer, and then click Continue. You'll then have to wait for the email to show up in your inbox (should be a few seconds). Make sure the email is the latest one. Gmail, for example, will connect all messages with the same subject ("Sign in to Sirepo") into a single thread so just make sure it's the last one in the thread. Once you click on that link, you'll be logged in. 

Only then you can move on to the next computer, and repeat the process.

**Comment by smlund** [comment]
Rob,


Sorry for my delay in reply. I will call.


I *am* only using the link once and attempting to login from another computer.  I also closed browsers on other computers where I tried to login.  I just tried again.  It does not work.  I get the same expired link message on FIRST click.


Thanks,

Steve


________________________________

**Comment by robnagler** [comment]
@smlund I've refreshed your last login link so it will be good till tomorrow afternoon. If you need to login to other computers, I can make the link work again once you use it. Just email me. Sorry for the trouble.

The problem is the same as #1987 but this particular robot is hiding itself as `Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)`

**Comment by robnagler** [comment]
Corrected to #1937
