### ISSUE TITLE
server side app structure

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#1990]
Currently for each app, for example srw, we have a file structure like this:

template/srw.py
template/srw*.py -- other sirepo srw specific modules
sim_data/srw.py
pkcli/srw.py

So when you are developing sirepo, you'll have multiple srw.py files open, but need to use the directory structure to know if you are working on the pkcli vs the template or sim_data module.

A better structure might be creating a sirepo/app directory and then placing all the necessary server files there:

app/srw/sim_data.py
app/srw/template.py -- "template" isn't a great name
app/srw/pkcli/srw.py

or something similar. Possibly sirepo itself could be one github repo and sirepo srw could be a separate github repo containing all the srw related files.

**Comment by robnagler** [comment]
It's kind of  a chicken and egg problem, and this doesn't solve the js, json, or html directories.

There should be one pkcli for running all codes, and that pkcli loads classes that handle the protocol (run, run_background). We have that now with job_process, essentially, which could also wrap the other command line invocations so they wouldn't have to run through pkcli.

I think there are two types of code adapters: metadata and execution. Metadata should be completely independent of the code. This is called sim_data (for now).  Metadata should just be a description Execution contains wrappers for the code. Execution wraps the code and deals with things like SDDS and HDF5, which should not be in the server/flask.

Once the job code is deployed, we'll have more separation, but as we know, we need more. There can be no imports of other codes directly, for example.

I think therefore it is premature to define a structure. We should formalize more of the interfaces including the request-response structure including getApplicationData.

**Comment by robnagler** [comment]
The more I think about this, the more this is a bad idea. We are constantly changing interfaces to Sirepo, because we are using emergent design. I changed pkconfig recently to remove the load path concept, and it was very easy to do, because it was "designed in", and I didn't have to visit 10 different code files to remove append_load_path. That can be one lazily. However, if the reverse was true, and I wanted to add append_load_path, I'd have to find all repos that implemented it, which are many. This is obviously the flip side of emergent design, but it was faster, because deleting an interface is a lot faster than adding it when there are existing uses. Creating it in the first place was fast, because there were no uses.

The point I'm making is that with emergent design, mono  repos are easier. You can synchronize changes much more easily. I think that's the reason Google stays with a mono repo. 

I find that I'm making changes all over the place when there are "plugins", e.g. I just added [`USER root`](https://github.com/radiasoft/containers/blob/1be655de968b2df201539cd57f2e7026fe1fbb83/bin/build-docker.sh#L37) to radiasoft/containers, and there are many uses, in many repos. I had to make sure that change didn't break anything. It would have been easier if there had been one repo with all container config so I could find it all.

When we change from AngularJS to whatever, it will require knowing all the code. The same thing when we change to Py3. I don't think we are nearly ready to support "plug ins" for codes.

Also, until we have fixed template to support inheritance and to encapsulate the interfaces clearly, we will be touching code all over the place. I don't see us getting done with this redesign for another year. I would say at that point, we would be able to consider moving around the code adapters. However, it should include the Javascript so that won't happen until we define the interfaces to codes. This too will require polymorphism.

**Comment by robnagler** [comment]
I think we have to fix both the server and client.

**Comment by robnagler** [comment]
package path takes care of enough of this, and ngui will handle this better.
