### ISSUE TITLE
srw: performance comparison of single threaded jobs on NERSC

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2118]
If a user had a priority queue on NERSC, would there be a performance advantage to running single-threaded beamline simulations vs. on a sirepo server. What is the performance of a single-threaded job for a complicated beamline on NERSC.

**Comment by robnagler** [comment]
Shifter startup can take minutes on a compute node. Submitting to sbatch can take 10 seconds. There is also a slowness in that you have to login to NERSC. Network transfers would be slower, because they are going over the Internet vs a local 10gbe. With our local cluster, startup time is less than a second.
