### ISSUE TITLE
email login on firefox shows error in logs

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2130]
When you login via email with Firefox, after hitting the confirm button this error appears in the logs and briefly flashes onscreen. The app continues normally after that. This error didn't show up in Chrome or MS Edge.

![Screen Shot 2019-12-17 at 2 49 17 PM](https://user-images.githubusercontent.com/6516910/71037178-6c4b7580-20dc-11ea-8e59-fc014a64e4a3.png)

**Comment by robnagler** [comment]
This is due to the fix for #2071. If we set the reload timer to 100ms, it doesn't show the error, because Firefox can finish loading the page from the cache. I'm guessing that FF is just slower than the other browsers. 

We can detect FF and add 100ms delay.

Or, we can fix the app so it doesn't have to reload when the user authenticates.
