### ISSUE TITLE
Slurm node state down

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2136]
Leaving this here for myself or anyone else who runs across this.

Jobs submitted to sbatch were stuck in the 'pending' state because the localhost node was down on my vm. (`sinfo` reported: debug*       up   infinite      1   down localhost)

`systemctl status slurmd` reported slurmd was running but there was an error:
error: Node configuration differs from hardware: Procs=2:4(hw) Boards=1:1(hw) SocketsPerBoard=2:1(hw) CoresPerSocket=1:4(hw) ThreadsPerCore=1:1(hw)

The solution:
`sudo su -`
`scontrol`
`update NodeName=debug State=DOWN Reason="undraining"`
`update NodeName=debug State=RESUME`

**Comment by robnagler** [comment]
Easier syntax especially for executing from python:

```sh
sudo scontrol << EOF
update NodeName=debug State=DOWN Reason="undraining"
update NodeName=debug State=RESUME
EOF
```

**Comment by mkeilman** [comment]
I got this but seemingly for a different reason.

```
scontrol show node localhost
NodeName=localhost Arch=x86_64 CoresPerSocket=1 
   CPUAlloc=0 CPUTot=2 CPULoad=0.21
   AvailableFeatures=(null)
   ActiveFeatures=(null)
   Gres=(null)
   NodeAddr=localhost NodeHostName=localhost Version=19.05.8
   OS=Linux 5.11.22-100.fc32.x86_64 #1 SMP Wed May 19 18:58:25 UTC 2021 
   RealMemory=1 AllocMem=0 FreeMem=5278 Sockets=2 Boards=1
   State=DOWN ThreadsPerCore=1 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=debug 
   BootTime=2021-07-26T12:50:11 SlurmdStartTime=2021-07-20T14:04:39
   CfgTRES=cpu=2,mem=1M,billing=2
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
   Reason=Node unexpectedly rebooted [root@2021-07-21T13:55:28]
```

Looked at the config page [here](https://slurm.schedmd.com/slurm.conf.html) to find this:

ReturnToService
Controls when a DOWN node will be returned to service. The default value is 0. Supported values include
0
A node will remain in the DOWN state until a system administrator explicitly changes its state (even if the slurmd daemon registers and resumes communications).
1
A DOWN node will become available for use upon registration with a valid configuration only if it was set DOWN due to being non-responsive. If the node was set DOWN for any other reason (low memory, unexpected reboot, etc.), its state will not automatically be changed. A node registers with a valid configuration if its memory, GRES, CPU count, etc. are equal to or greater than the values configured in slurm.conf.
2
A DOWN node will become available for use upon registration with a valid configuration. The node could have been set DOWN for any reason. A node registers with a valid configuration if its memory, GRES, CPU count, etc. are equal to or greater than the values configured in slurm.conf. (Disabled on Cray ALPS systems.)

Checking:
```
scontrol show config
...
ReturnToService         = 1
```

which I guess means that "unexpected reboot" does not qualify as "non-responsive".  I edited ``` /etc/slurm/slurm.conf``` to set ReturnToService to 2 then ran ``` sudo scontrol reconfig```  and that cleared things up.  Whether that's general enough to fix the original issue I don't know...
