### ISSUE TITLE
run parallel simulation not working on alpha

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2164]
* Partially Coherent Radiation
* Start
* End
* Refresh
* Start

**Comment by robnagler** [comment]
This is still happening on a zgoubi example, too. It's not easily repeatable, but it may have something to do with the browser tab going to sleep.

**Comment by e-carlin** [comment]
I haven't gotten to a working solution yet but I think I've identified 2 bugs and 2 possible solutions that can fix this.
1. api_simulationFrame jobs and api_runSimulation jobs need to be scheduled in a coordinated manner in the agent. Sometimes, a runSimulation is sent at roughly the same time as a simulationFrame. If the runSimulation beats the simulationFrame it will delete the runDir and then the simulationFrame will get an error (No such file or directory) because the runDir cannot be found. What I haven't yet figured out is how the computeJobSerial check doesn't prevent this from happening. My guess is it is some asynchrony that happens after the check.  *Solution* - coordinate these two jobs. We discussed yesterday (and I agree after investigating) that the agent should not let a runSimulation start while a simulationFrame is running. A problem this solution doesn't fix is if the runSimulation starts and then the simulationFrame starts all will work but the GUI could be requesting simulationFrames for an old simulation. I don't think this will lead to any problems but it isn't 'right'. Maybe the supervisor should check the computeJobSerials still match _after_ the [response is received](https://github.com/radiasoft/sirepo/blob/f771f2abb75d627aa31638a8c7dcaaeeebb19029/sirepo/job_supervisor.py#L340)?
2. The api_simulationFrame request fails because the computeJobSerial [check fails](https://github.com/radiasoft/sirepo/blob/f771f2abb75d627aa31638a8c7dcaaeeebb19029/sirepo/job_supervisor.py#L335). I think again this has to do with timing between the api_simulationFrame request and api_runSimulation request. The GUI is sending api_simulationFrame for an out of date computeJobSerial. @robnagler can you remind me why we have the [retry](https://github.com/radiasoft/sirepo/blob/f771f2abb75d627aa31638a8c7dcaaeeebb19029/sirepo/job_supervisor.py#L328) in this piece of code? *Possible solution* - Do not assert the computeJobSerial matches. _Check_ if the computeJobSerial doesn't match and if so reply with something (maybe? state=canceled).

@robnagler I'm going to start implementing these solutions. Let me know if you have any thoughts.

**Comment by e-carlin** [comment]
@robnagler for docker parallel sims the analysis jobs are sent to the same **host** but not the same **agent** ([see here](https://github.com/radiasoft/sirepo/blob/f771f2abb75d627aa31638a8c7dcaaeeebb19029/sirepo/job_driver/docker.py#L70)). So, the agent is unable to prevent a new compute job from starting while an analysis is running because they involve different agents. How should we proceed?
Possible solutions:
1. Make analysis jobs for parallel sims use the same agent.
2. Prevent the supervisor from sending any compute jobs until all outstanding analysis jobs for the jid have completed. In addition, don't send any new analysis jobs until we have received a response from the agent that the computeJob has started.

**Comment by robnagler** [comment]
I think the (2) because the supervisor is the only one that can actually control things. For example, if a compute job is running on sbatch followed by an analysis, these would have to complete before a new compute job running on docker. 

The supervisor scheduler has to be more sophisticated. I think we should discuss in person to walk through this.

**Comment by robnagler** [comment]
https://github.com/radiasoft/sirepo/issues/2126#issuecomment-566263152 explains the retry.

I think this is also a result of scheduling. The supervisor jumps the queue for cancels, which is fine, but then it flushes the queue, which maybe it shouldn't.

**Comment by robnagler** [comment]
Worked on this state map of transitions from API event when op in pending state:

![State map for incoming API when pending op](https://user-images.githubusercontent.com/5495179/72197258-870fc200-33dc-11ea-9346-7d0d8a472911.jpg)

**Comment by robnagler** [comment]
@e-carlin please review [JobManagement wiki](https://github.com/radiasoft/sirepo/wiki/JobManagement). I tried to capture was in the picture.

**Comment by robnagler** [comment]
Added what happens when ops are queued: https://github.com/radiasoft/sirepo/wiki/JobManagement

**Comment by robnagler** [comment]
To simplify state management, we should queue APIs on input. This will give us a handle to manage the queued operation that can be "replied to" independently. This will simplify the logic around state transitions, I believe.
