### ISSUE TITLE
text for email login could be expanded

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#2186]
This is what a user sees after entering their email address to login,

![image](https://user-images.githubusercontent.com/3825435/72446701-4368df80-3771-11ea-8ce3-719ef9001efe.png)

If they have incorrectly typed their email address, then they may be confused and may think the Sirepo login procedure is broken.  Same problem if the Sirepo-generated email goes to their spam filter.

It might be a good idea to expand the text, suggesting these possibilities to a new user.

It might make sense to specify the 'from' address and/or the subject line of the auto-generated email, in case they need to go looking for it.

**Comment by robnagler** [comment]
A longer text will not necessarily help the user. Here's what medium.com has:

![medium-login](https://user-images.githubusercontent.com/5495179/72453099-d0189b00-377b-11ea-950c-15aa59a1dc43.png)

I think we could do a better job of notifying the user once the email was sent. We could actually try to validate the email address before closing the window. Many SMTP servers (MTAs) will reply with the failure nowadays, because they are trying [to eliminate backscatter](https://en.wikipedia.org/wiki/Backscatter_(email)#Connection-stage_rejection). We could take advantage of that, and try to get the reply from our SMTP client.

We could also receive the email of the bounce programmatically, and take action inside the app to contact the user. This probably would require websockets between the app and the user. This might be a better approach, because then we could automatically reload the page when the email link is clicked.

Another approach is to monitor the bounces, and try to contact the user. We could have a dashboard of outstanding unverified emails that allows admins to get more information, e.g. originating IP (which may not be included in a bounce). 

Although, in my experience, users will mistype email addresses, and generally get confused about logging into sites. It's not something we can completely eliminate. It's probably the biggest support issue for most sites.
