### ISSUE TITLE
fixups run each report call

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2202]
It looks like fixups get run every time a report is requested on the incoming data. Instead, the version should be passed from the client along with the data, and fixup only run if needed.

**Comment by robnagler** [comment]
Similar to #266. I think this is the wrong issue. #277 is relevant also and #355.

The fix to this should be to have save simulation return the simulationSerial. Then, runSimulation should accept simulationSerial plus any operational parameters (report and ???). simulationSerial should be validated against sirepo-data.json atomically in the supervisor. If the simulationSerial is wrong, collision is returned. If it is correct, the simulation is run by copying sirepo-data.json with operational values to in.json. This would fix most of the issues except #355, but even then, #355 could be fixed by having it compare the simulationSerial (returned with each report) to show it was valid.

You would never need to run fixups on runSimulation.

I don't think this is a big change, just require runSimulation to wait for any outstanding saveSimulations to complete.

**Comment by robnagler** [comment]
See #4174
