### ISSUE TITLE
illegal name from server is not handled in client

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2228]
The client validates the simulation name and folder name, but at least one example has an invalid name, SRW's "NSLS-II HXN beamline: SSA closer". That makes it impossible to create a new copy of that simulation.

Also, the client is not checking for an illegal leading or trailing ".", so if you create a simulation with the name ".test", it will cause an exception rather than an error.

The client is already doing validation on the name. The server should strip out the bad characters in parse_name() and continue on.

**Comment by robnagler** [comment]
Be careful with parse_name as the value in `req.name` may not always be respected. When I was making the parse_params change, I couldn't fix up all the places where values were used as they weren't cascaded properly. For example, `data.models.simulation.simulationName` is not being fixed up by parse_name so it might pass through directly instead of using `req.name`
