### ISSUE TITLE
Enable GitHub login

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#234]
Use OAuth.

**Comment by robnagler** [comment]
Give user the option to "continue as guest" but want them to login at GitHub. Perhaps consider continue as guest just for SRW calculators.

**Comment by mrakitin** [comment]
I feel that the priority for this issue needs to be raised. A scientist here at NSLS-II performed some important calculations a week ago, then cookies were cleaned up in his browser, so he is now not able to see his calculations, and I had to grep a bunch of calculations to find what he needs and restore access to the simulations. That's very inconvenient and highly possible to happen again for other users.

I wrote backup instructions at https://github.com/radiasoft/sirepo/wiki/Backup-SRW-Sirepo-simulations, but we definitely need a login feature, so that all simulations are linked to a particular user, not a browser (cache/cookies can be cleaned, browser can be changed, etc. which will cause more hassles in the future). Let's consider to implement it ASAP. Adding @ochubar.

**Comment by robnagler** [comment]
It is a priority. I'm first cleaning up the logging issue. I had to fix
other bugs first. I will first implement the db (#319) which will enable us
to add users and then I'll add GitHub login.

**Comment by mrakitin** [comment]
I like this plan. Thanks Rob!

**Comment by robnagler** [comment]
Allow for the possibility of logging in from other OAuth providers. This means the db binding will need to know which OAuth provider was used to login with which user name. In contrast, JupyterHub uses the simple name from the OAuth provider, because it doesn't allow multiple OAuth providers.

**Comment by robnagler** [comment]
@moellep Let's get GitHub login working. All we have to do is bind the user id to a name. We can keep a simple file with a threading.RLock lock to get going. We can model after jsfiddle.net or plnkr.co. 

Some thoughts for $.02:

* Login link appears in upper right when they haven't logged in.
* Once logged in, we have the logout link go into the gear menu, because we don't want them logging out (just like they can't log out now).
* For starters, once they login, we take the original directory.
* For simplicity, I think we should denormalize the github idea into a file in the user directory. That file might contain other info like user_is_admin.
* We don't need an auth protection, since the user is in the cookie and the value is a secret (never exposed).
* For starters, anonymous cookie user is deleted if logging into an account that exists under another cookie user. No need for merge for SOS2016.

Secondary considerations:
* Consider merging cookie users by looking for modified examples by last modification time on the date of the db save.
* User name in log.

**Comment by mrakitin** [comment]
What if the internet connection will not be available for local installations?

**Comment by robnagler** [comment]
It will work as it does now. You don't have to login to use it. We can make
GH login feature configurable to the installation if this becomes a
problem/confusing.

**Comment by mrakitin** [comment]
Great!

**Comment by robnagler** [comment]
We decided to not implement this now. It's too risky to implement a significant feature to the workflow the week before the conference. We'll focus on stability.

**Comment by bruhwile** [comment]
This is 1st Priority again.

**Comment by robnagler** [comment]
I was working with @elventear on Jupyter/Hub on generalizing integrations yesterday. I think we may want to change this task to be "launch from Juypter", and let JupyterHub handle the authentication. There is still work in enabling authentication, but it's about binding the internal user to the external user, not about the GitHub workflow, which admittedly is fairly straightforward.

In any event, let's talk before this happens. @elventear will be working on enabling Jupyter to launch arbitrary components (right now the text editor, terminals and notebooks are someone hardwired). These efforts should be coordinated.

**Comment by bruhwile** [comment]
Executing Sirepo-based GUIs from within JupyterHub would have some
important benefits:

1) Exporting a flat Python script from the GUI would become more valuable,
because users would have the option to immediately execute the file inside
a Jupyter terminal.

2) Likewise, our idea of exporting IPython notebooks would work very
naturally.

3) Related to 1), this would facilitate a feature request from some
potential users, who asked about command-line access to generated files
even while using the GUI. This runs somewhat against the whole idea of
using a GUI in the first place, but it is potentially a reasonable workflow
for experts...

On the downside, it's not clear whether one could retain the present
no-login-required feature of Sirepo, which is very attractive. Maybe a
user's first interaction with Sirepo would be the same as now, independent
of Jupyter, and then when the user requests a persistent account, they are
redirected to a JupyterHub login, after which they discover all their
previous simulations are there waiting for them...? That would be cool.

**Comment by robnagler** [comment]
This would work quite similar to what we have now, because Jupyter, by default, is loginless. 

It's important to understand the difference between JupyterHub and Jupyter. JupyterHub is not related to Jupyter except that it passes some environment variables to a spawned process (Start My Server) which Jupyter (the spawned process) uses to identify the user, directory, etc. This decoupling is powerful, because it allows us to [execute a script](https://github.com/radiasoft/containers/blob/master/radiasoft/beamsim-jupyter/radia-run.sh) that sets up Synergia (among other things) and then start Jupyter.

Our work would be to extend Jupyter (not JupyterHub) to launch a configured URL based on a file type. It does this now for notebooks (ipynb) and text files, but is not really generalized. We could technically adopt the ipynb format and bind a Jupyter kernel with Sirepo, but I don't like this approach, because it is too tightly coupled. We wouldn't be able to do this for proxied services like COMSOL, which need this same mechanism.

Instead, we would add another handler similar to [the terminal handler](https://github.com/jupyter/notebook/blob/master/notebook/terminal/handlers.py) that would load an HTML file, which would then redirect to Sirepo, passing on the authentication token. Essentially, all we have to do at this point is to accept the token along with some user info (directory, GitHub login name, etc.), and run Sirepo on that. This will require some changes to Jupyter, but they aren't extensive as it has mostly modularized how handlers work (they aren't dynamically configurable, which is what we need).

What will change is eliminating the file browser from Sirepo. Rather, Sirepo will run on file (and related directory). This is related to the self extracting archive idea, but we don't have to do the self-extracting part, rather, we point the python server at a particular directory, and it operates on that directory. Some file format changes will be required, but they aren't extensive, because of the way @moellep brilliantly architected Sirepo's database. :)

I also think this will solve some versioning issues, because the redirect will be able to look at the Sirepo database file to determine which version of Sirepo (or docker container) was used, and can see if we want that to be "fixed" (reproduce, please) or not (just use the latest, default).

In some sense, this is extending Jupyter to dynamically invoke a web server (or reverse proxy for COMSOL), possibly inside a docker container, that accepts a particular authentication protocol. This is what JupyterHub does, but it doesn't bind the execution to anything in particular (read: python notebook or Sirepo input file).

So, the workflow is not exactly as you describe. We can have an open server approach similar to [try.jupyter.org](https://try.jupyter.org) for people to launch Sirepo without logging in. From there, we could have a button to the GitHub authenticated JupyterHub, which would redirect around a bit to get to jupyter.sirepo.com (or something similar), which would sort out all the cookies and binding an existing anonymous user to a regular user. It'll be a bit of logic, and the redirects will have to manage the cookies properly, but we can get it to work.

I guess this may all be a bit difficult to visualize, and it all comes under TL;DR, but I feel like it is important to document this thinking as I just refreshed it in the conversation with @elventear yesterday. It was not obvious at the beginning of the conversation that this is how it would work, but we eventually came around to the above approach.

**Comment by moellep** [comment]
After review with @robnagler - need add a lock around sql calls in sirepo.oauth and move the _move_user_simulations() logic from oauth into simulation_db and use the simulation_db lock.

**Comment by robnagler** [comment]
This has been installed on beta.
