### ISSUE TITLE
pkcli.roles should allow lookup by email

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2410]
If not found by uid, lookup by email if configured.

**Comment by e-carlin** [comment]
@robnagler in order to access user emails sirepo.auth.email will need to be initialized. This has some required values (ex smtp_password). Will those be in the environment when you run the cli on the server? Should I make an initialization fn for just the db that the pkcli can call so we don't have to set all of the configuration values?

**Comment by robnagler** [comment]
Yes, the environment in the shell is always complete. That's why we have [`env` as a separate script](https://github.com/radiasoft/rsconf/blob/f24cb38ca4/rsconf/systemd.py#L107) in the configuration.
