### ISSUE TITLE
fete warpvnd download data file on conductor grid gets 404s

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2438]
I'm working on this as a part of #1560 and #2427 (restructuring download_data_file).

**Comment by e-carlin** [comment]
#2429 is possibly related.

**Comment by robnagler** [comment]
It's fundamentally flawed API, because there's no report directory. The error showing up is:

```txt
'PKDict' object has no attribute 'jobRunMode'. 
```

But the problem is that no reports are run, and the download data file is a menu item on the Conductor Grid, which is not a report. In order to generate the python file, it has to have a run directory to be able to write the parameters.

@mkeilman Has this ever worked?

**Comment by mkeilman** [comment]
I can't recall ever trying it. Since it's just a preview I suppose it's not a meaningful item to include in that menu...

**Comment by moellep** [comment]
It used to work and worked the same way on the "Raw Data File" download on the lattice diagram on elegant/synergia/zgoubi. I couldn't find a way to get it to work so I took it out of those apps because it isn't a necessary feature - the python source is already available from the cog wheel.

Set the "hasDataFile": false in the view schema and it will remove the "Raw Data File" option for the report.

https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/json/elegant-schema.json#L3968

**Comment by robnagler** [comment]
I'll make that fix, and remove it from get_data_file. Simplifies the code further.

We need to reconcile the word "report" with analysis model and "computeModel". The only thing that had a runDir is a computeModel. Analysis happens after a computeModel is run. 

The way the code is written, I don't think it could have worked even in the old days, because get_data_file was called [without creating run_dir](https://github.com/radiasoft/sirepo/blob/92c52271349e9403b504121f4a9d6cfb86dc6beb/sirepo/server.py#L147) and get_data_file [does not create run_dir](https://github.com/radiasoft/sirepo/blob/92c52271349e9403b504121f4a9d6cfb86dc6beb/sirepo/template/warpvnd.py#L197). 

This could work as getApplicationData, but it still needs a directory to run, or render_jinja should be fixed to not write a file. It's problematic if it writes a file anyway.
