### ISSUE TITLE
asyncio.CancelledError inherits from BaseException in > py 3.8.x

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2447]
This doesn't need to happen soon, but it will break things, and I wanted to put a placeholder. It may be that we do this when we upgrade to fedora/3x

**Comment by e-carlin** [comment]
This needs to be fixed in fedora 36 migration

**Comment by e-carlin** [comment]
Something to note https://github.com/tornadoweb/tornado/issues/2990 . Specifically that Tornado support for cancellation is "limited" and this bug has been open for almost 2 years.

**Comment by e-carlin** [comment]
As part of this work I was looking at this code https://github.com/radiasoft/sirepo/blob/645410aaa0d49e37b99ef61426646e6e22465a83/sirepo/tornado.py#L50

In it we suppress CancelledError which seemed strange to me. I'm definitely not 100% confident in my understanding of CancelledError and so maybe I'm not understanding this code. But, in the event that a task is canceled and that task is waiting on [`return await x`](https://github.com/radiasoft/sirepo/blob/645410aaa0d49e37b99ef61426646e6e22465a83/sirepo/tornado.py#L49) when it is canceled. Then I don't think that task will be properly canceled because the CancelledError doesn't get the ability to bubble all of the way to the top.

In > py 3.8 CancelledError is a subclass of BaseException. To modify this code to keep the existing behavior on py 3.7 that would mean changing the code to [explicitly catch CancelledError here](https://github.com/radiasoft/sirepo/blob/645410aaa0d49e37b99ef61426646e6e22465a83/sirepo/tornado.py#L54). But as I described above I think that could result in a task not fully canceled. 

@robnagler what do you think about this?

**Comment by robnagler** [comment]
Cancel is [re-raised](https://github.com/radiasoft/sirepo/blob/645410aaa0d49e37b99ef61426646e6e22465a83/sirepo/tornado.py#L77) so I believe it is correct.

We should remove the cancel code in the supervisor, but that's a big project.

**Comment by e-carlin** [comment]
Ah indeed! Thanks for looking.
