### ISSUE TITLE
authentication expired but re-authenticate does not work for guest

### ISSUE THREAD

**Issue by ahebnl** [radiasoft/sirepo#2458]
Guest Access Expired: To continue using Sirepo we require you to authenticate using email.You will use this email to access your work going forward. Please click here to authenticate.

"click her to authenticate" have no response after long waiting. For Chrome "Clearing the browser data" did not work, restart Chrome did not work. But open a different browser, IE, works as a new guest user.

**Comment by robnagler** [comment]
This is for your local server, not sirepo.com, because we don't support guests on sirepo.com any more.

The easiest workaround is to increase the timeout:

```sh
export SIREPO_AUTH_GUEST_EXPIRY_DAYS=1000
```

For a long term fix, I would suggest you require email authentication. This is important for environments where you have multiple users so you can identify which user is bound to which simulation.  It also allows users to see their simulations on multiple devices.

To configure email auth, you'll need to setup some parameters:

```sh
export SIREPO_AUTH_EMAIL_FROM_EMAIL='<who the mail comes from>'
export SIREPO_AUTH_EMAIL_FROM_NAME='BNL Sirepo Support'
export SIREPO_AUTH_EMAIL_SMTP_PASSWORD='<smtp account password>'
export SIREPO_AUTH_EMAIL_SMTP_SERVER='<smtp server>'
export SIREPO_AUTH_EMAIL_SMTP_USER='<smtp account user>'
export SIREPO_AUTH_METHODS='email'
```

You need to have access to an SMTP server which can send outgoing mails. This might be an internal mail server, if you only expect @bnl.gov addresses.

This would require all users to login the first time. Email logins don't expire.

You could also configure GitHub authentication, but that requires all users to have GitHub accounts, and for GitHub to be accessible. It uses OAuth. The steps to setup on GitHub are a bit complicated so we could perhaps do that on Skype. You would probably want an organizational account.

**Comment by robnagler** [comment]
@ahebnl is this issue resolved?
