### ISSUE TITLE
Permission denied: '/global/cscratch1/sd/nersc'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2483]
I'm logged in correctly, but it is using the wrong value for the login name to create the scratch directory path.

**Comment by robnagler** [comment]
I was not able to reproduce this problem. I might have typed `nersc` when I was logging in the second time after the login succeeded but failed to connect in the websocket.

**Comment by e-carlin** [comment]
Is this the events you're thinking of:
1. You try to login in using your nersc creds
2. Agent doesn't connect in time so we report to the GUI that login failed
3. Agent connected
4. You login again but this time type `nersc` for your username.
5. You run into permission denied problems because you are trying to read/write to the `nersc` users files

I left [some comments](https://github.com/radiasoft/sirepo/pull/2491#discussion_r422210743) on #2491 relating to this sort of a problem.

**Comment by robnagler** [comment]
Yes, that's probably what happened. I'll answer the other comments directly. Once logged in, we should never get to this place, but since there was a bug, this allowed the "hack" you discussed.
