### ISSUE TITLE
missing animation directory breaks simulation

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2518]
Similar to the earlier report bug which has been fixed - if you run a long-running job and then delete the animation directory, the report shows an error and the simulation can never be successful run again.

To reproduce: in SRW run the Partially Coherent Results simulation. Then delete the simulation's multiElectronAnimation directory and refresh the browser page. The "Report not generated" error is shown in the report panel, and selecting the "Start New Simulation" button results in "server error".

**Comment by e-carlin** [comment]
Couple problems here:
1. Just a bug. [This should be prev_db not self.db](https://github.com/radiasoft/sirepo/blob/a0c8e6ad055ce51e0811cdb9b842f59bedc7e5bf/sirepo/job_supervisor.py#L413). That will make it so the user can click  run simulation and have it not result in an error. I'll write a test to cover this. But, this doesn't solve the `report not generated`.
2. Solving report not generated. What leads to report not generated is: we runStatus and get back 'cancelled' (or whatever the status of the job was according to the supervisor db). But, really the run dir is missing so the status should be 'missing'. The supervisor has no way of knowing that the run_dir is missing without starting an agent and asking it. 

Solutions to problem 2:
1. Do nothing. The only time user run_dirs will be deleted is when they are purged due to being a free user. In this case the supervisor state is set to 'job_run_purged' so we don't get into this problem. If the run_dirs are deleted from something else it is a bug.
2. We could make sim frame requests tolerant of state 'missing'. In the case of missing they would just display nothing.
3. On run_status we could start an agent. This is a fairly large change for our code. I need to think more about the impacts.

My vote is #1. Run_dirs should only be deleted through a known mechanism and we won't run into this problem. For dev's who are deleting run_dirs (or a user who's run_dir was deleted by a bug) they will get `report not generated` and then be able to click `run simulation` which seems fine.

@moellep  @robnagler  thoughts?

**Comment by moellep** [comment]
No. 1 sounds fine to me.
