### ISSUE TITLE
Radia geometry directory breaks encapsulation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2598]
Similar to #2065 but more problematic. There seems to be a directory "geometry" that holds results that is independent of run_dir. This won't work on NERSC, and Radia is supposed to work on NERSC.

We need to keep to the concept of run_dirs and not invent new directories. We shouldn't see code like this:

```py
def _get_res_file(sim_id, filename):
    return simulation_db.simulation_dir(SIM_TYPE, sim_id) \
        .join(_GEOM_DIR).join(filename)
```

_GEOM_DIR is not a computeJob run_dir. It's problematic to refer to sim_id within code templates as well. The run_dir is an abstraction that has nothing to do with simulation_dir on the server. They are in fact completely different roots on NERSC and the server.

The exception in #2597 was caused by this improper use of simulation_dir and simulation_ids.

What we can have is a single computeJob that stores the state. Then, if some reports need the state, they will run off the same computeJob run_dir. This is what elegant does, for example.

**Comment by e-carlin** [comment]
@mkeilman is running up against this right now trying to get radia working with sbatch. Since this issue was opened we've created the [sim_db_file API](https://github.com/radiasoft/sirepo/blob/6fbf8035c63e4c332270913011aa35f33331ede5/sirepo/pkcli/job_supervisor.py#L49) and I think sharing the geometry.dat using it makes sense. I'm going to spend a few trying to get it working. Let's discuss more in the SW meeting tomorrow.
