### ISSUE TITLE
Payment routing

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2655]
This issue needs more specification- The basic issue is the need to pull the payment process to Sirepo.com from RadiaSoft.net and address some user journey issues.

**Comment by robnagler** [comment]
I need clarification on what you would like. It's unclear what it means. If it means hooking up a payment  processor like Stripe so that subscriptions are fully automatic, I think we should discuss the value of this as opposed to, say, streamlining the invoicing process for organizations (e.g. labs) that will not be paying by credit cards.

**Comment by messamer** [comment]
[PaymentWireframe.pdf](https://github.com/radiasoft/sirepo/files/5017288/PaymentWireframe.pdf)

Here is my proposed solution- happy to brainstorm.

**Comment by messamer** [comment]
[PaymentWireframe.pdf](https://github.com/radiasoft/sirepo/files/5017440/PaymentWireframe.pdf)

Here is my proposed solution- happy to brainstorm.
