### ISSUE TITLE
SRW - Export/Import of simulations inconsistency bug

### ISSUE THREAD

**Issue by DmitrySmalyuk** [radiasoft/sirepo#275]
1) **Description:** When a simulation's python code is exported after the Initial Intensity Report on the Beamline page has finished calculating, the "distance from source" parameters of all reports on the source page are reset to the nominal position of the first optical element on the beamline page.

**Example:** Open [this simulation](https://alpha.sirepo.com/srw#/beamline/oTGfBqjw?show_item_id=PglV7dzD). Note that the reports on the Source page are all 26 meters from source, while the first optical element is at 40 meters from source. Wait for this simulation to finish calculating the reports on both the source and beamline pages. Export python code of this simulation. Import the python code to a new simulation. Note that, in the imported simulation, the reports on the source page are all 40 meters away from source, even though they should be 26 meters from source.

 2) **Description:** When a simulation's python code is exported before the Initial Intensity Report has finished calculating, the nominal position of the first optical element is reset to the "distance from source" value of the reports on the source page. All other elements' nominal positions shift as well, preserving distances between elements.

**Example:** Open [this simulation](https://alpha.sirepo.com/srw#/beamline/VEwP43vJ?show_item_id=VEwP43vJ). Before the Initial Intensity Report on beamline page is calculated, export this simulation's python code. Import the python code in separate browser tab. Note that, in the original simulation, the first beamline element is at 20 meters, and the reports on the source page are at 30 meters. Now note that, in the imported simulation, the first beamline element is at 30 meters.

**Comment by mrakitin** [comment]
We can implement exporting of Python code for a particular report and exporting of JSON file for the whole simulation and importing of both formats - JSON (the most reliable way to transfer a calculation) and Python (user cannot 100% trust the imported results since the beamline may be shifted due to the `v.op_r` parameter can be changed (e.g., for the Flux report) and the user will be importing exported Python file for this report).

Ticket #243 will take care of JSON files. The rest can be implemented within this ticket or we can create a new one and mention the motivation came from this issue.

**Comment by mrakitin** [comment]
This is an important request, since the exported Python files are inconsistent with what a user wants to calculate after the export. Need to implement a report-level exporting of Python files. I needed it much during the past several weeks of real calculations.

**Comment by mrakitin** [comment]
While I was working closely with the SMI beamline scientist to perform SRW calculations in Sirepo, I needed to export a Python file for partially-coherent calculations many times, but Sirepo exported an arbitrary file with
```python
    op = None
    v.ss = True
```
or something like this, but we needed to have:
```python
    op = set_optics(v)
    v.wm = True
```
That's pretty inconvenient to change it manually every time. That's why we need to have the export procedure for each report, since it's going to be used much in the nearest future.

**Comment by mrakitin** [comment]
Thanks Paul for implementing it in ed1c4e5. I tested it briefly, and it works great so far. Closing this ticket.
