### ISSUE TITLE
Remove 'madx' if m == 'madx' else 'py'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2794]
I don't understand why pythonSource would ever end in `madx`. What is going on in this code?

```py
    return _safe_attachment(
        flask.make_response(
            req.template.python_source_for_model(d, m),
        ),
        d.models.simulation.name + ('-' + title if title else ''),
        'madx' if m == 'madx' else 'py'
    )
```

**Comment by moellep** [comment]
```api_pythonSource(simulation_type, simulation_id, model=None, title=None)```
should be renamed something like:
```api_simSource(simulation_type, simulation_id, model=None, title=None, format='py')```

For applications like JSPEC and OPAL, the simulation source would not be python, but the native input file. This would address #2269 

The current "Export as MAD-X Lattice" feature would use the format='madx' argument rather than passing 'madx' as the model name. I'll open a new ticket for this.
