### ISSUE TITLE
Consolidate APIs for fetching template data

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#3015]
We currently have multiple ways to get app data from templates, either for download (.py, .zip, etc.) or for use on the client. The idea for this change is to have a single class-based interface with methods that templates can override when needed.

Any correction or clarification of the title or this comment is welcome :-)

**Comment by robnagler** [comment]
Other issues to consider:

- api_downloadDataFile should have computeJobSerial #2304
- rename APIs to eliminate unused params and convert GETs to POSTs #2801
- getApplicationData via job_api #2201 -- create archive should go to job supervisor, since it could take a while.
- Need structure to server API requests and responses #422 -- specifically that we should understand how to know if the request fails in a consistent way (state=error or whatever)
