### ISSUE TITLE
Update wiki for Running jupyter lab in the VM

### ISSUE THREAD

**Issue by dtabell** [radiasoft/sirepo#3124]
In the instructions for [Running jupyter lab in the VM](https://github.com/radiasoft/sirepo/wiki/Development#running-jupyter-lab-in-the-vm), three methods are listed (because they're listed in the `jupyter lab` output) for connecting one's browser to the running JupyterLab. However, of the three methods mentioned for connecting,

- `file:///home/vagrant/.local/share/jupyter/runtime/nbserver-...`
- `http://v4.radia.run:8888/?token=...`
- `http://127.0.0.1:8888/?token=...`

only the middle one works. The first complains “File not found”, which is surely because, in fact, no such directory exists on my Mac. And the last complains “Unable to connect”. Not sure if these errors are particular to Mac OS, but I think it would be good to mention the problem and stress that the middle option is the best (only?) choice.

**Comment by dtabell** [comment]
An update to the above: I found that even though the VM lives on my local machine, I *still* require an internet connection to access it. This seems somehow utterly bizarre. I mean, it shouldn't need a DNS to identify `http://v.radia.run:8888` as my machine, right? If there's a way to fix that issue, please also include that in the updated wiki.

**Comment by mkeilman** [comment]
I have updated the wiki.   Notes:

- The URLs that jupyter refers to are relative to the VM - nothing specific to Mac OS, it's just assuming you'll use a browser on the same machine as the server.  The wiki now calls that out.

- As for v.radia.run, it seems that an internet connection is required at least on a Mac in order to resolve it (I don't know why it works that way, or whether other OSes also do it).  Otherwise you have to use 10.10.10.10 explicitly.  You can add ```10.10.10.10     v.radia.run``` to your Mac's ```/etc/hosts file``` (it's read-only so use sudo) which lets you access the VM without internet, but I don't know whether we want to direct users that way?
