### ISSUE TITLE
runCancel causes server error

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#330]
The client call to runCancel is missing the simulationId:

File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 593, in _job_id
    return '{}-{}-{}'.format(simulation_db.user_id(), data['simulationId'], data['report'])
KeyError: 'simulationId'

To reproduce - open warp with a with a beam example, change the density slightly and select "save changes". The error will appear in the server logs.

**Comment by robnagler** [comment]
I can't reproduce this after the other fixes. Let me know if you see the error on your server.

**Comment by robnagler** [comment]
Thanks @moellep for helping to reproduce. The problem is in [clearFrames](https://github.com/radiasoft/sirepo/blob/1a02e6c00a920b44618114b62cc7b4b93efaacde/sirepo/package_data/static/js/sirepo.js#L416) which passes incorrect params to runCancel.

There shouldn't be a runCancel in clearFrames, and in fact, there shouldn't be a clearFrames call to the server. Instead. the server/client should detect parameter changes and update accordingly. More Issues coming.
