### ISSUE TITLE
Announcements for Sirepo and Jupyter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3314]
There is this https://github.com/rcthomas/jupyterhub-announcement but I don't think it would work well. We need to add something to JupyterLab.

I think Sirepo should have similar announcements. We would want to say "system maintenance 1/25/21 10:00-10:10". It needs to be built into the system like jupyterhub-announcement, because we need to do it before a release. I don't think we need a history or multiple announcements. It should be very simple so that JuptyerLab could pull the same notification and display it however it could display it.

**Comment by bruhwiler** [comment]
This is in regard to a referring issue located here, https://github.com/radiasoft/ops/issues/624

I realize the referring is being added here as a subset to a larger issue; however, this is a serious problem/bug that needs to be resolved as soon as reasonably possible.

Here is the text that is presented to first-time Sirepo/Jupyter users now --

500 : Internal Server Error
Error in Authentication.pre_spawn_start:_Error HTTP 403: error (You have not been allocated any servers. Please contact support@radiasoft.net.)
You can try restarting your server from the <home page>.

Here is the requested text --

Thank you for registering to use Sirepo!
You are welcome to use Sirepo's integrated JupyterHub server.

First time JupyterHub users must be whitelisted, in order to keep cryptominers out of our system.
If you don't hear from the Sirepo support team within 2 business days, please email support@sirepo.com

In the mean time, feel free to use any of our other Sirepo apps!

Sincerely,
The Sirepo support team.

**Comment by robnagler** [comment]
This is multiple issues. Most important is https://github.com/radiasoft/rsdockerspawner/issues/26
