### ISSUE TITLE
handle verify_app_directory in audit_proprietary_lib_files

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3351]
It may raise an error. In the normal course of operation of sirepo this is probably fine. In the db upgrade this is a problem.

**Comment by robnagler** [comment]
We had a discussion about "catch exception", and I said that was a bad idea. Here's the code that usually gets written:

```py
try:
     something()
except KeyError as e:
     handle()
````

We then try to handle KeyError, which I have seen (many times) to be a different KeyError than what was being handled, because `something` calls `otherthing` that gets a KeyError for a very different reason. In this particular case, we can throw a special exception (either via the message being unique or a unique class) that is "sure" it is for this particular error, and not for another spurious reason.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/pull/3352/commits/0a4621a987b37046a6a8ad7f334ce86089367ef5#diff-e84e9d79eaa4edd99f619a565b48b1af12560478b238cb008a3a46e105922d96R69 now passes in the uid. By supplying the uid a different code path is taken and sirepo.auth.user_dir_not_found() will never be raised.
