### ISSUE TITLE
building a simulation programmatically

### ISSUE THREAD

**Issue by jklynch** [radiasoft/sirepo#3702]
Is it possible to programmatically build a simulation? By that I mean is there an API that allows one to create a new, empty simulation and then add components?

I am mainly interested in this for writing automatic tests for sirepo-bluesky.

**Comment by robnagler** [comment]
The JSON is the API for the most part. You need to understand the schema of the specific code in order to use it.

There is [sirepo.lib](https://github.com/radiasoft/sirepo/blob/master/sirepo/lib.py) which allows you to start with a simulation in the native format, and then create a Python dict (a sirepo.lib.SimData object). There is also an export feature from sirepo.lib that allows you to convert the SimData back to native format. Currently this works with elegant and opal, but we could expand the codes. 

@jklynch we'll be discussing this tomorrow in our collaboration meeting.

**Comment by robnagler** [comment]
To document with this issue, here's some code written by @e-carlin to use `requests` to talk to the Sirepo server to access a simulation. The problem was the bootstrap to get a simulation id, not to create an arbitrary simulation from scratch with the API.

```py
"""Example http client to interact with Sirepo

PREREQUISITES:
- the requests library (`pip install requests`)
- Sirepo running with guest auth enabled (`sirepo service http`)

This creates a _Client object that can log into Sirepo and retrieve
a simulation id for a simulation with a known name.

:copyright: Copyright (c) 2021 RadiaSoft LLC.  All Rights Reserved.
:license: http://www.apache.org/licenses/LICENSE-2.0.html
"""
import requests

class _Client:

    def __init__(self, host, sim_type='srw', sim_name='NSLS-II ESM beamline'):
        self._session = requests.Session()
        self._sim_name = sim_name
        self._sim_type = sim_type
        self._host = host

    def get_simulation_id(self):
        r = self.post(
            '/simulation-list',
            {'search': {'simulation.name': self._sim_name}},
        )
        assert len(r) == 1, \
            f'expecting only one simulation with name={self._sim_name} found {r}'
        return r[0]['simulationId']

    def login(self):
        """Get cookied. self._session will preserve the cookies""""
        r = self.post('/simulation-list', {})
        assert r['srException']['routeName'] == 'missingCookies'
        self.post('/auth-guest-login/' + self._sim_type, {})

    def post(self, path, data):
        data['simulationType'] = self._sim_type
        r = self._session.post(
            f'{self._host}/{path}',
            json=data,
        )
        assert r.ok, f'response={r} not ok'
        return r.json()


client = _Client(host='http://127.0.0.1:8000')
client.login()
print(f'simulation_id={client.get_simulation_id()}')
```
