### ISSUE TITLE
../sirepo/util.py:222:in_flask_request flask.request is False

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3810]
@e-carlin should this be coming out normally?

**Comment by e-carlin** [comment]
Where are they coming out?

In flask there are some at initialization. For example, the db_upgrade code triggers it. Once up and just serving requests we shouldn't see anymore.

In the supervisor they will appear throughout the life of the process. They can be ignored since we are interested in what's going on in flask.

**Comment by robnagler** [comment]
I can ignore them, but they are coming out when I run commands. Do we know when we are in pkcli vs flask? If so, maybe ignore there?

**Comment by e-carlin** [comment]
There is the [`is_server`](https://github.com/radiasoft/sirepo/blob/b8ad2d5e6b5e54b2a343025e9bcbef1bc5ac464d/sirepo/server.py#L639) flag we could use. Maybe set it on srcontext? Need to think about it more.

**Comment by robnagler** [comment]
Yes, something like that. I don't know about srcontext or not.

**Comment by moellep** [comment]
For more context, we shouldn't see the "util.py:273:in_flask_request flask.request is False" messages when running command line utilities like "sirepo admin create-examples".
