### ISSUE TITLE
sim_data.srw.srw_predefined with package_path

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3941]
We use '' as the filename in [srw_predefined](https://github.com/radiasoft/sirepo/blob/756d475a2add594b499089b106ac6b2284b758b3/sirepo/sim_data/srw.py#L395). 

This could fail if:
srw is added to package_path and the added package contains a [_TEMPLATE_RESOURCE_DIR](https://github.com/radiasoft/sirepo/blob/756d475a2add594b499089b106ac6b2284b758b3/sirepo/sim_data/__init__.py#L81) but that dir does not contain sirepo.template.srw_common.PREDEFINED_JSON

**Comment by robnagler** [comment]
Copied from https://github.com/radiasoft/sirepo/pull/3940#issuecomment-963366326:

I think srw_predefined and pkcli.srw.create_predefined should change. If the file isn't found, the exception needs to be caught, and create_predefined is called.

To find where to write the file in create_predefined, we could look for, say, parameters.py.jinja, and substitute srw_predefined.json, because this is the only write case. Alternatively, we could add a new entry point in sim_data that returns a non-existent file to an appropriate location, e.g. by looking at all dirs in the package.path, and returning the first non-empty dir.

**Comment by robnagler** [comment]
I'd like to bump the priority of this, because some of the recent changes are for BNL. I'd like to get it in an alpha this week.
