### ISSUE TITLE
enable use of blade + cloud-based VMs for Trieste demo

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#397]
We may have about 30 users during the demo on Thursday morning (European central time), October 6.
It would be great if we had enough processors to enable them all to use the code simultaneously.
This would also be an excellent test of the system.

**Comment by robnagler** [comment]
@moellep @elventear and I have a discussion about the feasibility of scaling automatically with AWS. 

The fundamental problem is that Sirepo relies on rapid polling of files for interprocess communication. The latency is too high between any two ISPs so the performance is going to suffer. 

For the purposes of SOS2016, the most important performance issues are the "quick" reports being as fast as possible and for the background jobs not to lock up the entire server. To fix the former problem, we have enabled a blade with 16 slots for simultaneously generating quick reports.  For the background queuing problem, we will use 2 blades initially configured with 4 slots with 4 cores each, which gives us 8 slots with a 4x speedup. We also have Flower installed which will allow us to kill jobs if users leave them running too long. The timeout is 12 hours so that's not going to be any good.
