### ISSUE TITLE
webcon: controls twiss parameters display

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4016]
The beam twiss parameters (hor/ver alpha/beta/emit) at each monitor could be shown, possible below each BPM/screen report, with the option to hide the information for all plots. A bonus would be to plot the twiss ellipse as an overlay on the BPM/screen reports

![Screen Shot 2021-12-21 at 3 27 34 PM](https://user-images.githubusercontent.com/6516910/147005825-1ffd73eb-b720-4745-8e14-897a4d7d4085.png)
.

**Comment by j-edelen** [comment]
This is not quite what I had in mind. I was thinking you could show the twiss report similar to the screenshot here but here the lattice is larger and on the bottom and the twiss report is on the top. Even though not all that information is available for tuning or control, it's a useful diagnostic and many people use on line models like this when operating the machine. 

<img width="802" alt="Screen Shot 2021-12-22 at 6 16 30 AM" src="https://user-images.githubusercontent.com/24392411/147098562-3dda3da5-53a2-4cbe-ac11-73a173e887de.png">

**Comment by dtabell** [comment]
Some comments from my perspective:

(a) I don't have a strong feeling about having the lattice above and Twiss report
below, or vice versa. Convention has it placed above, but I agree with Jon that it
would look better below—because the schematic lattice elements would appear
closer to the main action in the lattice function plots.

(b) I definitely agree about making the schematic lattice larger—more visible.

(c) I'd like to see some guides along the lines of the thin blue lines I’ve overlaid
on the figure below. Perhaps a checkbox to turn them on/off? (I chose blue, but
have no dog in that fight.)

(d) Paul’s idea of displaying the phase-space ellipse is an interesting one. The
absolute size will not matter without a value in hand for ε, but perhaps we could
display a small pair of ellipses (horizontal and vertical) below each of the markers
(and other elements of interest) showing their orientation and, if εx and εy are
known, their relative sizes. I think this could add considerable pedagogical value.

**Comment by j-edelen** [comment]
@dtabell, this is for the controls application display. The lattice is the primary view along with the beam parameters. I wanted to add in some beam envelope displays to this as well. This would allow for an on-line model in the same viewer as the controls synoptic display. The controls display is supposed to be dominated by measurables.
