### ISSUE TITLE
radia: pkio.py_path.local does not exist

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#4077]
In ```pkcli/radia.py```: ```template.extract_report_data(pkio.py_path.local(cfg_dir), data)``` fails because py_path has changed. Modify to ```pkio.py_path(cfg_dir)```

**Comment by robnagler** [comment]
I'm really confused. `pkio.py_path.local` was never a method afaict. The last update to pkio was in Nov 2021. How was this ever working?

**Comment by e-carlin** [comment]
This was a bug I introduced in a0b337565115171acde548ce42fab05ad6f7d12f. pkcli.radia was using `py.path` directly. I changed the the import do be pkio and then only half fixed the actual use.

**Comment by e-carlin** [comment]
To be clear - nothing about pykern has changed.

**Comment by robnagler** [comment]
d000560 shows this was the old code:
> template.extract_report_data(pkio.py_path.local(cfg_dir), data)

This code could never have worked.

**Comment by e-carlin** [comment]
From oldest to most recent the changes are 
`py.path.local(cfg_dir)` (0d66efb464b48609f15fdaaa7b9fdd5442519d6f)
`pkio.py_path.local(cfg_dir)` (a0b337565115171acde548ce42fab05ad6f7d12f)
`pkio.py_path(cfg_dir)` (d000560544b05df55d425013713b5d533a434345)

In a0b337565115171acde548ce42fab05ad6f7d12f I got rid of `py.path` (because we use pkio to wrap py.path) and changed it (incorrectly) to `pkio.py_path.local`.  

You're correct that in d000560544b05df55d425013713b5d533a434345  the old code doesn't work. That is the code Mike is fixing that I introduced while, sloppily trying to, refactor from `py.path` to `pkio.py_path`.
