### ISSUE TITLE
camelCase vs snake_case

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4205]
Our code is a bit confused on camelCase vs snake_case. The schemas are mostly camelCase (though not all). The js is all camelCase. The json payloads are camelCase and then they trickle through the python so there is a mix of snake vs camel case. As part of ngui we may want to consider fixing this.

I don't have any strong opinions on how it should be done but here are some ideas:
1. we write everything in snake case
2. js stays camelCase except json is all snake_case 
3. everything stays the same except we write some code that converts incoming json from camelCase to snake_case.

I'm sure there are other ways to handle this. Opening the issue to discuss other strategies and whether this is a problem worth solving.

**Comment by moellep** [comment]
I think the schema we need to be flexible with naming. I've found it best to tie the model field names directly to the underlying simulation code. For example, elegant's bunched_beam model has an emit_nx field or zgoubi's QUADRUPO model has a CS_2 field. This wasn't done for SRW and it was a mistake because it makes it much harder to determine that sphericalMirror.normalVectorX actually corresponds to SRWLOptMirSph.nvx.

**Comment by robnagler** [comment]
I agree with @moellep. However, "our" names should resolve to what we want them to be, which I think is what @e-carlin is really asking about.

Also, I would like to get rid of URLs entirely. They can just be the name of the entry point into the GUI. If we need to alias, we can just create an alias JS name.  The same thing for the server API.

**Comment by robnagler** [comment]
We are going to be flexible on naming.
