### ISSUE TITLE
madx import fails: >=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#4216]
Importing a MADX file to elegant that was exported from https://www.sirepo.com/opal#/visualization/3CeErNY9 gives an error:
`'>=' not supported between instances of 'str' and 'int'`

[CM_test.txt](https://github.com/radiasoft/sirepo/files/8201348/CM_test.txt)
`

**Comment by gurhar1133** [comment]
Doesnt work in madx either. gives this error:
```
warning: illegal expression set to 0 in: real gamma_x = ( 1 + pow ( alpha_x , 2 ) ) / beta_x 

warning: illegal expression set to 0 in: real gamma_y = ( 1 + pow ( alpha_y , 2 ) ) / beta_y 

Error: seterrorflag : Errorcode: 1   Reported from pro_twiss:

Error: seterrorflag : Description: TWISS failed

warning: Twiss failed:  MAD-X continues
```

**Comment by moellep** [comment]
I think this is related to MAD-X lack of support the pow() function in expressions. This case can be fixed by changing the OPAL simulation variables, replacing the pow() calls:
```(1 +pow(ALPHA_X, 2))/BETA_X```
to:
```(1 +(ALPHA_X * ALPHA_X))/BETA_X```

Here is the same OPAL simulation which can export to MAD-X, after replacing the pow() expressions:
https://www.sirepo.com/opal#/lattice/moo5tRwO

MAD-X does have a "^" operator for exponentiation. We could possibly convert pow(x, y) to ((x) ^ (y)) when generating the madx to solve this.

The error message Chris encountered should be improved at a minimum.
