### ISSUE TITLE
srw parallel partially-coherent calculations

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4245]
> For some reason, parallel partially-coherent calculations stopped working for me from Sirepo since maybe couple of days.
> A test simulation never seems to produce the “Partially Coherent Intensity, 49.2m” report where running at NERSC in debug queue. The calculation starts, I see “Initializing Simulation…” in the web browser, I see the job running in by squeue, but never a plot in my browser in 30 minutes. On the other hand, the Sirepo-generated script (attached) runs perfectly well at NERSC from a slurm script in the same debug queue.

I'll forward the email separately.

**Comment by e-carlin** [comment]
I think the problem is this https://github.com/radiasoft/sirepo/blob/3ba0a2e18a941104546208c6eaf4b6af39d06c73/sirepo/template/srw.py#L2052. In the nersc case the number of cores can be something large (ex 512). Which means srw will do many iterations before a save (I think, I'm not exactly certain how this code impacts srw). 

@moellep can you shed some light on how this code works? It seems that when I run a simulation with a small number of cores (haven't fully tested but 5 or less works) then particles complete (in a few minutes) and I get back the report . If the number of cores is large (ex 512) then no particles complete (I've run for as long as 20 min) and so no report is generated.

**Comment by robnagler** [comment]
That's right. The higher the number the longer between saves. This could be a wrong value:

```py
    ['sm_ns', 'i', {{multiElectronNumberOfIterations or 5}}, 'saving periodicity (in terms of macro-electrons) for intermediate intensity at calculation of multi-electron spectrum in case of arbitrary input magnetic field'],
```

Essentially, this seems to be `n^2` for saves, since the primary process waits for all worker processes to complete an iteration and counts that as one. So with 512 that's 262K macro electrons. 

This used to be fixed at 5 and f528e9d4620877d708e944d2b53f3c9ce60932f2 changed that to this number. Perhaps it was to try to fix the writing performance issues of the coherent modes report, which was fixed a different way in the end. @moellep?

**Comment by moellep** [comment]
It looks like it was always setting v.wm_ns to sirepo.mpi.cfg.cores (since 2019)

https://github.com/radiasoft/sirepo/commit/8951a17ce85879718fd545a5f3ee4b377786eb78

It was overriding the default value 5 in the simulations even then, I think. Unless that code was generating incorrectly, I don't see why it would have stopped working recently.

**Comment by robnagler** [comment]
@e-carlin you should test these commits to see what types of parameter.py files they generate. Clearly 8951a17 changed something and it may have broken something. Maybe the values weren't carried right in the pre-2019 version. It wouldn't have been used much at that time.

**Comment by e-carlin** [comment]
After discussion we decided that the number of processes is not a good value to use to determine `multiElectronNumberOfIterations`. So we're going to go with 25 in slurm and 5 everywhere else.
