### ISSUE TITLE
Play with React

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4255]

**Comment by e-carlin** [comment]
If it helps, here is my messing around https://github.com/radiasoft/reactapp/tree/e-carlin

**Comment by robnagler** [comment]
One thing I would like to know is how does React re-render? Does it compute the "highest element" in the tree and render everything below, or is there some optimization? Does re-rendering involve a call to a "render" method in the element itself? (I think that's how it works.) Is Redux making any decisions about rendering, or is simply the callback hook that Redux uses on the element that triggers React to re-render?

One of the problems we have is that we know something a lot about our data. We have a schema would could allow us to know which element is hooked it. I believe we should have an active request to the data object (unnamed) that will return the data value. How that happens is not important (e.g. xpath or simple js refs). The key is that the element should express interest in a data element. 

Consider a call like self.get('tabulatedUndulator.undulatorType') (never mind the naming for now) that gets this particular element. If it changes, we can know that self should be notified that it changes (never mind the update model). 

If React renders "down graph", then all we need to know is the top level unrelated nodes in the graph in order to force react to re-render. This could be solved with some type of weighted graph connected to the schema. Then we would have solve the [lowest common ancestor](https://en.wikipedia.org/wiki/Lowest_common_ancestor) for all nodes that changed only re-render those nodes that are "unrelated" LCAs. React probably has to do the same thing for figuring out what to rerender.

The nice thing about knowing all the data centrally is that the data are updated in chunks (today the whole thing is the most common). We can know a lot about what elements to notify that neither Angular or React/Redux knows anything about. We can have a "dirty tree" to find the LCAs on, and then make a few render calls to those elements and their children.

**Comment by garsuga** [comment]
React is actually very straightforward assuming we stay aware of a few catches with the way things work. Let's look at components assuming they are defined as 'function components' since these are the newest format for components and do a good job not hiding how things work. 

A function component is just a function in the shape (props: {[key: string]: any}) => React.Component
"props" refers to a map of attributes the parent passed to this component.

'State', 'Lifecycle hooks', and other patterns are handled by 'hooks'. Hooks are a broad topic but most hook are either the ones provided by React like 'useEffect', 'useState', 'useSelector' (not to be confused with useSelector from react-redux) or a function which utilizes them.

I think looking at 'useState' will answer a few of your questions. A code snippet using useState in a function component might look like
```
let SomeComponent = (props) => {
    const [x, updateX] = useState(0); // useState takes a default value as a param and returns the current value and a callback to update that value
    return <div>{x}</div>
}
```

In this case useState initializes x to 0 in the first render and will have this value persist in future renders if a few conditions are met. Other hooks follow the same conditions.
- A component with the same 'key' attribute is present in the next render of the parent. Keys are compared using '==' not '==='

OR

- The same function component (same function) appears in the same index of the children of the parent in the next render. It is very important to remember that in JSX an 'undefined' is passed to an index when conditionally excluding that element. The 'index' here is referring to the index passed to React.element, not the index of the children in the final DOM

AND in either case

- The parent met these conditions for its parent

With the useState hook, if the update callback was called then a new render of the hooked component and its children would happen. These updates are grouped somewhere in the React lifecycle but I am not familiar with how that works.

Hooks are stored by their order accessed in the context of the parent. While any function can create elements in React, only function components can use hooks. Function components are passed as a function to React.element and called by React. In JSX they appear as an HTML tag starting with a capital letter. A useful resource for looking at how hooks work is [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html). Put simply, they are functions that maintain some state on the parent element that the parent will conditionally persist into new children.

> Does it compute the "highest element" in the tree and render everything below, or is there some optimization?

No, it re-renders the component where a hook says it should and all children of that element. 'Rendering' is the process of calling a function component and combining these trees. React will compare the new tree with the existing one in the DOM and only update differences. All renders of a component will re-render its children by definition. A component is a function returning its children so all renders of a component will make a brand new set of children.

> Is Redux making any decisions about rendering, or is simply the callback hook that Redux uses on the element that triggers React to re-render?

For Redux, a hook called useSelector from react-redux handles re-rendering components by Redux itself does not handle rendering or hooks.

> The key is that the element should express interest in a data element.

To control rendering, place state (useState) in the highest component it is relevant to and pass references to this single copy of state downward or subscribe to global state (useSelector) where data is relevant. When using either useState and useSelector these calls should ideally be made only once for a tree and have their values passed to children using 'props' or by composing new functions.

> If React renders "down graph", then all we need to know is the top level unrelated nodes in the graph in order to force react to re-render. This could be solved with some type of weighted graph connected to the schema. Then we would have solve the [lowest common ancestor](https://en.wikipedia.org/wiki/Lowest_common_ancestor) for all nodes that changed only re-render those nodes that are "unrelated" LCAs. React probably has to do the same thing for figuring out what to rerender.

This problem should be avoided by placing relevant hooks for the data at the LCA and not at the leaves. This avoids the change propagation nightmare in Angular and makes data flow clear. The data for the leaves should be provided by the LCA so that multiple copies of the data are not maintained.

Hope this helps

**Comment by garsuga** [comment]
> React’s diffing algorithm (called [Reconciliation](https://reactjs.org/docs/reconciliation.html)) uses component identity to determine whether it should update the existing subtree or throw it away and mount a new one. If the component returned from render is identical (===) to the component from the previous render, React recursively updates the subtree by diffing it with the new one. If they’re not equal, the previous subtree is unmounted completely.

This is also an important note for making child components during renders.

**Comment by garsuga** [comment]
One issue I just ran into that is worth noting is that Reconciliation will always replace components that are created as new functions each render. This affects builder patterns like
```
let CreateMyComponent = (config) => (props) => {
    return <div>{config}</div>
}
```

In simpler usages it is easy to swap 'config' to be a prop but in more complex cases this can restrict you. Luckily only the top level call needs to be definite, the one passed to React.element or used as a tag in JSX.
The example above can be fixed simply
```
let DefiniteComponent = (props) => {
    let passedProps = { config, ...props };
    return CreateMyComponent(config)(passedProps);
}
```

This should also give a better look at how Reconciliation works with detecting changes in the trees.

**Comment by robnagler** [comment]
@garsuga et al I moved the [discussion here](https://github.com/radiasoft/reactapp/wiki/RenderDiscussion). I made some changes to enhance my understanding. I will read more to understand.

**Comment by robnagler** [comment]
I'm calling this done.
