### ISSUE TITLE
Strange error when logged out and go to shared link

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4337]
To reproduce:
- make sure you are logged out of sirepo.com
- go to https://www.sirepo.com/srw#/beamline/Fc7wsTmf?tab=multi
- see the error
<img width="1131" alt="Screen Shot 2022-04-18 at 4 52 56 PM" src="https://user-images.githubusercontent.com/10264515/163889801-853feb42-18a5-4443-b3e2-6dcefaea3726.png">

If you go to https://www.sirepo.com/srw#/beamline/Fc7wsTmf? (no `tab=multi`) then the link works.

**Comment by robnagler** [comment]
if the value doesn't conform, it should be encoded in the cookie at save time. this should be in sirepo.cookie. URLs cannot be expected to conform.

**Comment by moellep** [comment]
The client is storing the login-target in the cookie, so if you visit a link and are logged out, you will be redirected there after successfully logging in. Otherwise, if you visit a link when logged out, you would end up on the simulations page after logging in. The bug is that the url stored in the cookie needs to be encoded - in this case, I think the "=" in the url is corrupting the cookie.
