### ISSUE TITLE
Radia 3D visual axes do not update when mouse is outside visual

### ISSUE THREAD

**Issue by garsuga** [radiasoft/sirepo#4532]
The axes in the 3D 'Magnet Viewer' visuals do not update when the mouse leaves the bounds of the visual while clicking and dragging but the visual continues to update

https://user-images.githubusercontent.com/55895241/173963193-d84c8354-2d18-4247-8651-070e5b8be26d.mov

**Comment by mkeilman** [comment]
This happens because the event handlers in [sirepo-plotting-vtk.js](https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/js/sirepo-plotting-vtk.js) are on the render window:

https://github.com/radiasoft/sirepo/blob/13085266b8d5233882d74963b26a0a9510e3730b/sirepo/package_data/static/js/sirepo-plotting-vtk.js#L2584-L2589
...
https://github.com/radiasoft/sirepo/blob/13085266b8d5233882d74963b26a0a9510e3730b/sirepo/package_data/static/js/sirepo-plotting-vtk.js#L2616-L2617
...
https://github.com/radiasoft/sirepo/blob/13085266b8d5233882d74963b26a0a9510e3730b/sirepo/package_data/static/js/sirepo-plotting-vtk.js#L2647-L2654

So one option is to attach the handlers to a different DOM object like the body. Another option is to leverage vtk's [Interactor](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/RenderWindowInteractor/index.js) if possible.

**Comment by mkeilman** [comment]
@gurhar1133 this is not strictly speaking a radia issue but it will serve as a starting point. LMK if you have questions
