### ISSUE TITLE
20221115 refine persistent storage messaging

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4819]
Really a discussion topic: how to give users more information about run dirs that might be purged and/or users give the system a better idea of permanancy.

**Comment by e-carlin** [comment]
What type of users? 

For free users I don't think we need to give them any heads up or any options to mark permanency. That's part of the free tier agreement. 

For premium users our plan says "persistent data storage" so my understanding would be their data never gets purged so all simulations are "permanent" by nature of the plan they're on.

**Comment by robnagler** [comment]
With free users, we can delete their account or simulations source data (sirepo-data.json). 

With premium users, we don't guarantee that they can store simulation results forever.

**Comment by e-carlin** [comment]
Thanks

Here are my 2 cents although I think someone with the sales vision would have a better idea than me:

No marking permanency for anyone. I think it would cause more confusion than it will solve.

Free users: we can send them an email before purging their source data/account letting them know they need to log in to keep it from happening. No need to notify before purging results. 

Premium users: we can send an email letting them know their results will be purged after x days unless they interact with the simulation again.

Private: All purging is turned off

I think some of the current purge messaging needs to change because my reading of it is "if I upgrade to premium then my results won't go away". https://github.com/radiasoft/sirepo/blob/b2acdebf16b727913374c4711da91dae3ff41682/sirepo/package_data/static/js/sirepo-components.js#L1799

**Comment by robnagler** [comment]
I'll push this to the product management team.

**Comment by robnagler** [comment]
Remove the upgrade part of the message:

https://github.com/radiasoft/sirepo/blob/b2acdebf16b727913374c4711da91dae3ff41682/sirepo/package_data/static/js/sirepo-components.js#L1799
