### ISSUE TITLE
source term normalization

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4864]
This is a place-holder for an issue with more info. Cloudmc was demonstrated to the DAGMC group, and one of their suggestions was adding source-term normalization (multiplying heatplot values by a constant?)

**Comment by sjcrs** [comment]
Sure - since the tallies return are divided by the number of simulated particles to return a per-primary-particle result, the request is to element-wise multiply tally results by a scale factor to represent an exposure.

So, if I have a beam of neutrons that spills 10^12 neutrons every pulse, but I only simulate 50k neutrons for the sake of time, I want to be able to scale it up to the expected flux for for 10^12 neutrons.

**Comment by mkeilman** [comment]
> So, if I have a beam of neutrons that spills 10^12 neutrons every pulse, but I only simulate 50k neutrons for the sake of time, I want to be able to scale it up to the expected flux for for 10^12 neutrons.

Am I right in thinking this applies to only a subset of the tallies? Normalizing total flux makes sense, but I'm not sure about things like heating or reaction rates.

**Comment by sjcrs** [comment]
That's correct, any of the rates should not be scaled.

**Comment by mkeilman** [comment]
Here are the scores I have eligible for normalization. lmk if I have errors of inclusion or exclusion.

```
"flux",
"delayed-nu-fission",
"prompt-nu-fission",
"nu-fission",
"nu-scatter",
"H1-production",
"H2-production",
"H3-production",
"He3-production",
"He4-production",
"current",
"events",
"heating",
"damage-energy"
```
