### ISSUE TITLE
SRW - hide Mask element on production servers

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#498]
Development of the Mask element is far from its final stage and the ultimate goal, so per request of the Metrology group we should hide it on production servers of Sirepo (like alpha, beta), however it should be available for BNL installations.

@robnagler, any ideas about it? Probably we could introduce another environment variable like `SIREPO_USE_UNRELEASED_FUNCTIONALITY` or something like that. If it's false or not set, new functionality should not appear in Sirepo.

**Comment by mrakitin** [comment]
@moellep, we also need your help here. The problem is that the optical elements are statically defined in https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/html/srw-beamline.html#L38, and it's not trivial to remove them from that list dynamically (or with usage of a global variable). Can they be redetermined within `srw.js`?

I rather prefer to have them in the code and enable/disable them by a variable, than having a separate branch for it. Any objections?

**Comment by mrakitin** [comment]
@moellep, actually an optical element can be removed from the toolbox by commenting out corresponding line in https://github.com/radiasoft/sirepo/blob/master/sirepo/package_data/static/js/srw.js#L160, so no need in changing the behavior in `srw-beamline.html` at the moment.

**Comment by mrakitin** [comment]
Temporary solution implemented in 26b5c71 (mrakitin branch, will be merged later).

**Comment by mrakitin** [comment]
Hi Rob, please see the proposed implementation of the hiding procedure - fefbc8a. Any comments?

**Comment by mrakitin** [comment]
This can be enabled by:
```bash
$ SIREPO_SERVER_JOB_QUEUE=Celery SIREPO_SERVER_USE_NEW_FEATURES=True sirepo service http
```

**Comment by robnagler** [comment]
Odd, I wrote an email two days ago, but it doesn't seem to have been recorded in the ticket... Here it is again:

Keep the name the same throughout the app, ie. SIREPO.APP_USE_NEW_FEATURES.

I think it would be better to not have "hide" on the element, but instead, label the "feature type", e.g. sirepo_feature=SRW_MASK_ELEMENT. Then you would be able to control a set of different types of features based on a list. Instead of "USE_NEW_FEATURES", you would have a configuration "sirepo.feature.cfg.srw.mask_element" which would be true or false. The client would request this cfg (just like it requests the schema) to drive its app. You can define nested pkconfig. Look at sirepo.server.cfg.beaker_session for an example. 

Another issue is that I don't think this code should be on the client. schemas should be Python dictionaries (pkcollections.Dict) and then converted to JSON on demand. The Python dictionary would be edited on server boot to include/exclude features. The client would dispatch based on what features are available in the schema.

I know this is  a lot, and I'm not doing the coding. :)  However, I think having the discrimination logic on both sides of the wire is not the best approach.

I do think that the feature should be available on alpha. We should have all features available so that we can write tests against them, and have those tests run against alpha.

**Comment by mrakitin** [comment]
Thanks for your inputs Rob, but I'm not sure I have enough time to implement everything, especially the avoiding code on the client. It should be a fast implementation, so I'll change the first part to implement `sirepo_feature=SRW_MASK_ELEMENT`.

I agree about having these new features on alpha.

**Comment by mrakitin** [comment]
I'm not sure how are you suggesting to pass the values via `index.html`? Here is the code:
```js
    <script>
        var SIREPO = {
            APP_NAME:  '{{ app_name }}',
            APP_VERSION: '{{ version }}',
            SIREPO_FEATURE: {{ sirepo_feature }},
        };
    </script>
```

**Comment by mrakitin** [comment]
@robnagler, I'm confused by your suggestion. `sirepo.feature.cfg.srw.mask_element` means that I need to create a python module `sirepo/feature.py` and add `cfg.srw.mask_element` processing to it, right? If so, how to pass the config values from the command line or via global variables to `sirepo/server.py`? I'm currently passing the values to `sirepo service http`. Then it should go to `app_root(simulation_type)` to be transmitted to `sirepo/package_data/static/html/index.html` and finally to `sirepo/package_data/static/js/srw.js`. Please clarify the idea and the steps, I don't want to waste time. Thanks.

**Comment by robnagler** [comment]
I recommend a request like [app_simulation_schema](https://github.com/radiasoft/sirepo/blob/ed1765a44d1e25380d682d40346a47627dd09ae3/sirepo/server.py#L409). This would return the configuration to the client. 

The module `sirepo.feature` would just be a container for configuration. This would allow it to be decoupled from `sirepo.server`. This allows better modularization so that "lower" modules like the templates can refer to the configuration without having a circular import issue with `sirepo.server`.

The actual code that would do the processing should be in `sirepo.template.srw`. 

When you run `sirepo service http` you can pass any configuration parameter to it by naming it as an environment variable, e.g.

```sh
SIREPO_MPI_CORES=4 sirepo service http
```

When you configure the server (on debian) you would set it in `/etc/default/sirepo` or one of the other default files as appropriate.

**Comment by moellep** [comment]
Yes, the html file only defines the editor, it doesn't display it.
Conditionally adding the Mask for dev mode in srw.js makes the most sense.

@robnagler, is there a way to determine the config mode in the server and
have it populate the SIRPEO javascript constant?

**Comment by robnagler** [comment]
Keep the name the same throughout the app, ie. SIREPO.APP_USE_NEW_FEATURES.

I think it would be better to not have "hide" on the element, but instead,
label the "feature type", e.g. sirepo_feature=SRW_MASK_ELEMENT. Then you
would be able to control a set of different types of features based on a
list. Instead of "USE_NEW_FEATURES", you would have a configuration
"sirepo.feature.cfg.srw.mask_element" which would be true or false. The
client would request this cfg (just like it requests the schema) to drive
its app. You can define nested pkconfig. Look at
sirepo.server.cfg.beaker_session for an example.

Another issue is that I don't think this code should be on the client.
schemas should be Python dictionaries (pkcollections.Dict) and then
converted to JSON on demand. The Python dictionary would be edited on
server boot to include/exclude features. The client would dispatch based on
what features are available in the schema.

I know this is  a lot, and I'm not doing the coding. :)  However, I think
having the discrimination logic on both sides of the wire is not the best
approach.

I do think that the feature should be available on alpha. We should have
all features available so that we can write tests against them, and have
those tests run against alpha.

**Comment by robnagler** [comment]
Pkconfig has a channel value plus a test channel_in().

**Comment by mrakitin** [comment]
I don't have any progress on this issue.
@robnagler, do you mind to have a Skype meeting to discuss the details?

**Comment by robnagler** [comment]
I'm around all day except for the regular meeting.

**Comment by robnagler** [comment]
Added sirepo.feature_config with @mrakitin in  27c1a90. It's on by default in internal test (dev, alpha) so no additional configuration is needed. You can turn it off this way:

```sh
SIREPO_FEATURE_CONFIG_SRW_MASK_IN_TOOLBAR= sirepo service http
```
