### ISSUE TITLE
New source: 2D electromagnetic pulse with Gaussian profile (SRW Ex 7)

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/sirepo#5]
Add the ability on the 'source' page for users to specify a 3D electromagnetic pulse with a longitudinal Gaussian profile, with specified photon energy and energy spread, and with specified photon divergence. This would allow designers and users of beamlines at FEL light sources to get useful results from the SRW GUI.

Rob is taking the lead on this.

The "Gaussian beam" page on Wikipedia does a pretty good job of describing what's needed:
  https://en.wikipedia.org/wiki/Gaussian_beam 

A useful example of the SRW syntax can be found in the SRW GitHub repository
.../SRW/env/work/srw_python/SRWLIB_Example07.py
Look for 'GsnBm' and for 'wfr'

Implementation can be found here
.../SRW/cpp/src/core/srgsnbm.h  and .cpp

The above classes are invoked from here
.../SRW/cpp/src/lib/srwlib.h  and .cpp

**Comment by robnagler** [comment]
Changed the title , because the 3D electromagnetic pulse can be collapsed into a 2D slice. This is OK for two reasons:
  a) The sample at the end of the beamline essentially sees the longitudinally integrated pulse, so that's all the visiting scientists care about.
  b) Electromagnetics is linear, as long as material interactions aren't too intense, so you get the same result from a full 3D simulation as you do from modeling the integrated 2D slice.

SRW example 7, where a "Gaussian pulse" is treated as a 2D slice of radiation makes perfect sense.
@robnagler -- there is renewed interest in your work on this. It will immediately enable use of Sirepo/SRW for FEL facilities.

**Comment by bruhwile** [comment]
Paul completed this feature.
