### ISSUE TITLE
SRW - unnecessary recalculation of all reports on Beamline page

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#501]
Currently, if I change a position of the `Sample` on the `Beamline` page of the CHX example, all the reports are recalculated. This change should trigger recalculation of the last report only. I think previously it worked this way, but now it does not.

Please see https://alpha.sirepo.com/srw#/beamline/WIV0MjRC?application_mode=light-sources for details.

**Comment by bruhwile** [comment]
Some use cases are required to better define the problem.

**Comment by mrakitin** [comment]
The ticket is related to #504.

**Comment by moellep** [comment]
An example for this would be a beamline which contains several watch points. If you edit the position of the last watch point, the initial intensity and prior watch point reports do not need to get recalculated. The models_related_to_report() hook needs to be refined to allow returning the actual values the report depends upon, rather than model names.
