### ISSUE TITLE
20221202 LDAP: Create a new auth method (4 days)

### ISSUE THREAD

**Issue by Benbenbenin0** [radiasoft/sirepo#5151]
Create a new sirepo auth method using ldap. This will involve adding a module and required methods to sirepo/auth. As well as the GUI features to support it.

**Comment by robnagler** [comment]
We want to avoid creating new auth_db tables. I don't think we will need a new auth method table. Rather, we can reuse AuthEmailUser. This depends on #4872 and decoupling AuthEmailUser from sirepo.auth.email. I think the approach binding a method to credentials (auth_db record) is not the best. It worked with email and github, but email is the typical "user" credential these days. One thing we may have to do with the ldap auth method is provide a configured default domain so that we can create the AuthEmailRecord record when the user enters just their ldap user name (common case). This is normal, because there is only going to be one configured ldap server (for the foreseeable future).

**Comment by Benbenbenin0** [comment]
Method and basic UI in place

**Comment by e-carlin** [comment]
Is there a PR for this?
