### ISSUE TITLE
Hide point table for extruded object

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#5330]
Right now the table of points for an extruded object is at the top of the geometry tab which makes it less convenient to get to the editable information below the table.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/17073688/210857720-ce2db726-834c-47d2-b5d0-ec4befc750e7.png">

My preferred solution would be to keep the table where it is so it can be by the file import button but have it collapsed down with the option to click to expand the table.

Alternatively, the table could just be moved to after all the other fields, so that they can be accessed easily.

**Comment by mkeilman** [comment]
Something like this? With "input fields" replaced with text since they are not editable
<img width="954" alt="Screen Shot 2023-01-05 at 4 44 12 PM" src="https://user-images.githubusercontent.com/30352290/210901399-022c0e22-e8a4-4922-8598-d6b68796a46b.png">
<img width="954" alt="Screen Shot 2023-01-05 at 4 44 38 PM" src="https://user-images.githubusercontent.com/30352290/210901406-80ae17db-62ad-493a-ae1a-04d8b7743137.png">

**Comment by cchall** [comment]
Exactly! Looks great.
