### ISSUE TITLE
beta server restarted

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#568]
Not sure what was wrong, but simply restarting uwsgi/nginx didn't do it. 

Quiesced all services except rabbit and then started celery and then sirepo. Running ok now.

**Comment by robnagler** [comment]
We had another crash. It might have been triggered by elegant. To "fix" it, turned off flower. Didn't restart the sirepo itself, but uwsgi was pegged at 100% before stopping flower then the system stabilized. Stopping flower took ten or more seconds.

**Comment by robnagler** [comment]
More data. Seems that uwsgi is soaking up all memory then crashing. It is trying to process something after elegant runs. We have a reproducible case that works on Dev. @moellep is debugging.

**Comment by moellep** [comment]
The problem was the histogram bins selected was too high. In this case, the data file had the value of 20,000 which caused the numpy.histogramdd() call to exhaust the memory and crash. Celery may have then restarted the same task after the crash which made the problem worse. I'll open a new ticket specific to the histogram limit, but in general we'll need more testing of appropriate value ranges.
