### ISSUE TITLE
Decimation option for visualization

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5702]
We expect that some models will be too complex for navigation in the GUI. We've already seen slowdown with the Utah Teapot. We'd like to give the user a button to allow them to reduce the number of facets to speed up the visualization.

The difficulty here is that there are decimation methods to do this with STL files (http://vcglib.net/), I don't know how we do this with DAGMC/MOAB h5m files.

The end goal is to have a button that performs decimation on a copy of the geometry for visualization, but that a full-res version is used for the simulation.

This relates to Task 3 of the Phase 1, but i don't think it needs to be complete in Phase 1. I think it will suffice if we have a plan to address the problem for the Phase 2.

**Comment by moellep** [comment]
In the pkcli.cloudmc module, the dagmc file is converted to a series of vtk files, one for each volume grouping. This is used only for the UI, and those are the files would would be good to decimate. Depending on the input format required by the decimator, we could first convert to STL, process the STL, and then convert to VTK. The formats are very similar.

The first step would be to find a good library and algorithm which reduces the number of points. The next step would be converting a vtk-like data structure into the input required by the algorithm. Then convert back to VTK. Finally, integrate into pkcli.cloudmc.

**Comment by sjcrs** [comment]
I've used the desktop version of MeshLab for decimation in my workflows, so maybe that's a good starting place to hunt down the underlying methods

**Comment by moellep** [comment]
pymeshlab seems to be a good way to go. Using the meshing_decimation_quadric_edge_collapse filter with no options reduced the output file sized by 2 with no noticeable loss when viewing in the UI. In combination with the changes in #6048, extraction time was 5 times faster with 8 cores even with the decimation filter.

**Comment by moellep** [comment]
@Benbenbenin0 I've created a branch and added a simple call to decimate by 50%. This needs to be improved so that really dense meshes (like the Utah Teapot example) are reduced further, but sparse meshes (like the Tokamak Reactor) are not overly simplified.
![x](https://github.com/radiasoft/sirepo/assets/6516910/3cf4f0d3-6940-4376-b925-cd7926d89610)
vs
![x2](https://github.com/radiasoft/sirepo/assets/6516910/45c57f61-b77d-49c4-8b78-90ce25a72a06)

More info

pymeshlab filter
https://pymeshlab.readthedocs.io/en/latest/filter_list.html#meshing_decimation_quadric_edge_collapse

decimation paper
https://liu.diva-portal.org/smash/get/diva2:1320121/FULLTEXT01.pdf

Use this branch for the changes:
https://github.com/radiasoft/sirepo/commit/18fe3cf7a27e7a219fa510408fc583da455f1435

**Comment by sjcrs** [comment]
I also found this, which may be of interest: https://www.mmgtools.org/

**Comment by Benbenbenin0** [comment]
@moellep I just added `targetfacenum=MESH_MAX_FACES` to the decimation filter and set the constant to 10,000 (standard threshold for low-poly models).

This effectively decimates high-density meshes like 'utah-teapot' to low-poly and leaves already sparse meshes like 'Tokamak Reactor' untouched.

There is a way to iteratively calculate optimum decimation for each mesh, but for our purposes I think this is the fast, simple approach.

I've updated the branch, please take a look at the new decimation behavior when available.
