### ISSUE TITLE
uri_router is splitting url after decoding

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6211]
I think uri_router is splitting the decoded url, rather than the original, so %2F is being converted to / and then getting confused with the actual uri parts.

This came up in silas where there is a report titled "Radial/Axial Temperature Profile", and when that was included in the URL, uri_router complained about too many parts:

/python-source/silas/kXlg3AT3/tempHeatMapAnimation/Radial%2FAxial%20Temperature%20Profile

**Comment by robnagler** [comment]
Does this work in flask?

**Comment by moellep** [comment]
We determined this occurs before uri_router gets the data, and we should avoid having "/" in url data.

**Comment by robnagler** [comment]
> uri_router gets the data

Just to be clear, before Flask gets the data. Tornado gives you the path info unescaped. We could technically fix this for Tornado, since that's on prod. I think it's a bad idea to have "/" in uri components. In general we should avoid "/" in file names since they wouldn't work on most file systems.
