### ISSUE TITLE
importer_test.py fails with websocket timeout

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6619]
The importer_test.py is failing with websockets only, with a 20 second timeout. Is the timeout different for http vs websocket?

**Comment by robnagler** [comment]
This is a bit complicated. It doesn't fail on github actions or my vm with an appropriate value of `SIREPO_SRUNIT_CPU_DIV`. Use a higher value if your computer is slower. I could get it to fail if I set it to 25 on my VM. GH Actions uses 25 just fine, because their computers are faster (but fewer cores).

@e-carlin what value do you use and what's your clock rate?

**Comment by e-carlin** [comment]
Whatever the default is. I was running on a vm on our servers. 
```
$ lscpu | grep 'CPU M'
CPU MHz:               2199.986
```

**Comment by robnagler** [comment]
Try SIREPO_SRUNIT_CPU_DIV=50 to see if it passes. The default is 25. If it passes, try 37.
