### ISSUE TITLE
Implement fastcgi for sequential runSimulation

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6784]
Create an example test for comparing compute model vs stateful compute performance.

**Comment by moellep** [comment]
I've created a test branch which updates myapp with a new panel which calls either a compute model job or a stateful compute job.
https://github.com/radiasoft/sirepo/tree/6784-compute-model-perf

Open myapp and the Scooby Doo example sim, and select the buttons on the Test panel. Stateful compute is over 100x faster.

![x](https://github.com/radiasoft/sirepo/assets/6516910/06dc24e0-40f6-468e-9904-e2010656bd3f)

**Comment by robnagler** [comment]
Stateful compute is fast, because of "fastcgi". Here's a way to demo this:

1. Start the server
2. Navigate to Scooby Doo
3. Restart the server
4. Click Test Stateful compute

You'll see that it is slow, because the fastcgi server isn't running at startup.

It takes two seconds to start job_cmd, because it imports a lot. Nothing we can do about that.

This is why we wrote fastcgi (and why web servers create fastcgi, cgi being too slow).

This is part of the story. The other is runStatus polling, which can be eliminated now that the api server is running under Tornado.  I added a quick hack that eliminates the polling (b0600d1c) and here's the result:

![similar-times](https://github.com/radiasoft/sirepo/assets/5495179/37207868-27d5-42b5-9d0c-f3c27a86636f)

You can see the difference is 3.822 vs 3.681, 141ms. That's due to the second round trip to get the sequential result, which runs through fastcgi, but still takes some time.

Fastcgi works only with a command at a time. We could add another fastcgi instance for running sequential simulations in the agent. This would speed things up after the first sequential simulation, e.g. pages with multiple reports. For parallel jobs, it doesn't make sense anyway. 

For sequential jobs with fastcgi, we could have the result come back in the reply so there wouldn't need to be an round trip. However, this might cause a problem with Start Simulation buttons that want to display the status periodically like parallel jobs. Possibly, we could add a new API for this particular case, since it is most common, and only "Start Simulation" jobs show intermediate results.

The real fix for polling though still needs to happen both in the UI and job_api. This shouldn't be too hard to do. It's a question of priorities. Thoguhts?

**Comment by robnagler** [comment]
Fixed in https://github.com/radiasoft/sirepo/blob/839c8e6019c5eb2def368a6d77071e838ff291e6/sirepo/pkcli/job_agent.py#L172, but not yet released.
