### ISSUE TITLE
Geometry import is failing

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/sirepo#7078]
It appears that any new h5m geometry is failing on volume extraction.  Even ZPRE, which is in the example section, is not loading.  There are no error messages, but I suspect this has to do with our migration to pyDAGMC for volume extraction.

**Comment by moellep** [comment]
Could you send a link to your failing sims. I tried reloading zpre and it extracted ok.

**Comment by sjcrs** [comment]
https://www.sirepo.com/cloudmc#/geometry/zzwFZh8U

**Comment by moellep** [comment]
Several of your sims have had the underlying geometry file deleted. We only recently added a check so that when you delete a file, it ensures other simulations aren't depending on the file, so it is possible that you may have cleaned up your h5m file list before this feature was in place. I restored the zpre.h5m file so that simulation should work ok now.

**Comment by sjcrs** [comment]
That's weird, and feels like something that shouldn't happen for the
examples

**Comment by moellep** [comment]
Yes, I agree - I'll scan for other cases like this. For examples, you can always select "discard changes to example" to revert to the original form, and that would have brought the file back into sirepo.

**Comment by moellep** [comment]
I've verified that this problem didn't affect other users and removed your simulations which had the h5m file deleted. This problem won't occur in the future because of the bug fix in #6867
