### ISSUE TITLE
Cloudmc materials.xml import not working

### ISSUE THREAD

**Issue by mkilpatr** [radiasoft/sirepo#7124]
I've got a sample dagmc file and a materials.xml file to use as a test case for cloudmc work. I tried using the materials upload method that was recently developed, but after uploading none of the materials were applied to the volumes. 
[arduino.tar.gz](https://github.com/user-attachments/files/15826227/arduino.tar.gz)

**Comment by mkilpatr** [comment]
The sim I created as I tried to do this is here: https://www.sirepo.com/openmc#/geometry/f0WZXU9v

**Comment by moellep** [comment]
Two things need to be fixed in Sirepo for this:

- If the material name has a "mat:" prefix, it should be stripped before matching to the volume names.
- A material may not have a density value present if the selected units is "sum". In this case, the UI should accept a 0 density as a valid value and not continue to flag the volume as incomplete.
