### ISSUE TITLE
fete: lower limit on conductor size

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#814]
Conductors should have a minimum size of 0.5dx and 0.5dz (1/4 of a cell size). When a conductor which is too small is dropped or moved on the grid, an error message should be shown which recommends increasing the grid points.

**Comment by bruhwiler** [comment]
This issue probably merits a discussion. I think the dimensions should be fixed as an integer times dx and an integer times dz. Also, the lower edge (in both dimensions) should snap to the nearest mesh coordinate.

In the future, we could implement an 'advanced' mode where users can specify conductors that don't conform to the underlying mesh.

**Comment by ncook882** [comment]
I agree that this merits further discussion. I suggested sizes of 1/2 dx/dz based on both our experience placing objects combined with the observation that the epsilon grid for representing dielectrics is offset by half of a cell (cell-centered vs. node-centered).

We can certainly require that elements snap to the mesh with a specific orientation. This will minimize the likelihood of solver errors caused by a combination of the multigrid restriction parameter and the interpolation of the surface. It does seem that adjusting the multigrid parameter goes a long way towards accounting for nonconformal objects.

**Comment by ncook882** [comment]
If it's faster and easier to implement, it is fine to limit the size to integer multiples of dx and dz.

**Comment by moellep** [comment]
I think this issue has been solved in a better way with the fixed item "conductor must intersect grid #815".
