### ISSUE TITLE
Safely logout Sirepo?

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#835]
It seems that once a user is logged in using GitHub credentials, even after logging out from Sirepo, a user  could log in back without entering the password again. It does not seem safe on a public computers for the demo (e.g. at SPIE preparation computer I had to clear cache). Can it be improved?

**Comment by robnagler** [comment]
You have to logout of GitHub, too.

**Comment by moellep** [comment]
You don't need to clear the cache, but you do need to log out from both sirepo and github.com.

**Comment by mrakitin** [comment]
So, logging in to Sirepo will automatically log me in to github.com? If so, I'll do both logging outs. Thanks!

**Comment by robnagler** [comment]
No. Sirepo does not get your password to GitHub. Rather, in the process of logging to Sirepo, you have to login to GitHub directly in order to be authorized.

Technically, this could be considered an OAuth bug, but I don't really know the protocol that well. What GitHub is doing is validating your account and also setting a login cookie, when it really only needs to do the former and send the result back to Sirepo. However, it's easier for GitHub to just have one login process and validate the cookie in order to give OAuth approvals out that way.
