### ISSUE TITLE
prompt users to login with GitHub

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/sirepo#843]
We have two examples now, where a frequent (and very productive) user of Sirepo did not know about the GitHub login feature. This problem resulted in lost productivity for a busy scientist.

It has been suggested that we track the number of connections by a user who has not logged in. Once they have connected the 5th time (or some other modest integer), the UI should prompt them with some information about how to use their GitHub credentials to create a persistent work space.

Perhaps another approach would be better.

**Comment by mrakitin** [comment]
I would vote for immediate appearance of a dialog like
![image](https://user-images.githubusercontent.com/13209176/29197341-a3af2da6-7e08-11e7-8c19-17760a27fb97.png)
on access the Expert mode page. The words could be different (current snapshot is from the dialog when you log out).

As a side note, it would be good to have Google OAuth procedure implemented, since more scientists might have Google emails rather than GitHub ones. Facebook OAuth can be considered as well.

**Comment by bruhwiler** [comment]
The present operating mode, where no user login is required, remains an important and valuable feature of Sirepo. This lowers the barrier for new users to try it out. If possible, we should not prompt users to login, until they have clearly demonstrated an interest in using it repeatedly.

**Comment by messamer** [comment]
Is it the intent to have the login only when in expert mode?  I changed an existing simulation and expected the system to allow me to login to save it.  But, its not possible.... wouldn't we want people to make use of the examples?

**Comment by bruhwiler** [comment]
The idea for the simple examples was that they would be like calculators for people to play with -- not to save.  For example, if you click on the 'synchrotron radiation' examples, there is no beamline tab.  It's a different (simpler) experience.  However, we should reconsider. I agree that it's confusing if the behavior is so different, but the UI looks so much the same...

**Comment by mrakitin** [comment]
Related to #892.

**Comment by moellep** [comment]
closed with #892
