### ISSUE TITLE
No examples showing up on beta (new user)

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#989]
I went to Safari, cleared cookies, and clicked on expert users in SRW. The page doesn't show any examples even after a couple of minutes:

<img width="808" alt="screen shot 2017-12-31 at 2 03 28 pm" src="https://user-images.githubusercontent.com/5495179/34464197-8e99fdd8-ee33-11e7-912c-3ecab32af60f.png">

**Comment by moellep** [comment]
Did it eventually show up? I wasn't able to reproduce with a new user. There are times when beta become unresponsive. I filed #988 to help with this.

**Comment by bruhwiler** [comment]
The beta server was extremely slow yesterday (January 1). When trying to create a copy of a simulation, it took a full minute or more for the simulation page to appear.

**Comment by moellep** [comment]
Part of the problem may be the fix-ups get applied to each simulation when the list is generated for the simulation list page. This includes code which looks inside the zip files to setup the tabulated undulator defaults for old simulations. I've changed this a bit 37e607c so it will save these changes, rather than re-applying the fixups each visit. This isn't on beta yet.

**Comment by robnagler** [comment]
It's there now.  I just cleared everything and it came up within a few seconds. 

Let's ignore this unless it comes up again.
